### ISSUE TITLE
CCXT exchange potential bug.

### ISSUE THREAD

**Issue by diazagasatya** [tensortrade-org/tensortrade#135]
<em>Hey I think there's a potential bug in cctx_exchange.py line 140 and line 143. Please correct me if I'm wrong. </em>

In [ccxt_exchange.py](https://github.com/notadamking/tensortrade/blob/master/tensortrade/exchanges/live/ccxt_exchange.py), should it be referencing to `executed_order['status'] == 'open' instead of the regular Order object order['status'] == 'open'. This is also apparent in line 143.

As per class OrderStatus the enum reference of an 'OPEN' attribute is equal to 1 not 'open', hence I think you are referring to the executed_order from ccxt. Again, correct me if I'm wrong.

Cheers!

**Comment by coj337** [comment]
Can confirm it's an issue - addressed in #137
