### ISSUE TITLE
MinMaxNormalizer input_min default value is different in code and documentation.

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#139]
https://github.com/notadamking/tensortrade/blob/07f32447ef80d012a274623be5ebca4af03ceb25/tensortrade/features/scalers/min_max_normalizer.py#L30

https://github.com/notadamking/tensortrade/blob/07f32447ef80d012a274623be5ebca4af03ceb25/tensortrade/features/scalers/min_max_normalizer.py#L38

**Comment by mwbrulhardt** [comment]
`MinMaxScaler` is no longer in library.
