### ISSUE TITLE
`MinMaxNormalizer` produces incorrect results.

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#140]
`MinMaxNormalizer` seems to produce incorrect results as shown below.
```
import pandas as pd
from tensortrade.features.scalers import MinMaxNormalizer

normalizer = MinMaxNormalizer(columns=['A'])
df = pd.DataFrame({'A': [1, 2, 3]})
df2 = normalizer.transform(df)
print(df2)  # expected column A values are [0, 0.5, 1], actual values are [0.00001, 0.00001, 0.00001]
```

**Comment by YasserHassan** [comment]
I need to confirm my understanding before I submit a pull request. Are `input_min` and `input_max` used to clip input column values before scaling?

If so, they should default to None in my opinion to be used only if defined, otherwise they may cause an undesired behavior. For example, while an `input_max` default value of 1E8 should not affect price columns, it may do so when scaling the volume column or other indicators.

**Comment by mwbrulhardt** [comment]
`MinMaxNormalizer` is no longer in the library.
