### ISSUE TITLE
Enhancement: Add name specification for new columns in feature transformers

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#142]
I suggest adding an option to feature transformers to specify newly generated column names when `inplace` is set to False. That can give more control over the feature pipeline and help avoid possible problems. I suggest implementing this in one of the following ways:

- Add a new dictionary option to `inplace` as `{'col_name': True|False|<string>}` for column-level control. True/False will work normally while `<string>` is used to add and name a new column. Unprovided columns have the default value (`True`) applied to them.
- A new CopyTransformer is added just to copy specific columns to new one(s) with given names.

I recommend the first approach to simplify the pipeline creation and maintenance.

**Comment by mwbrulhardt** [comment]
Feature transformers are no longer used in the current setup at this time.
