### ISSUE TITLE
Feature Request: Add callable transformation to data source (Exchange/DataFeed)

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#143]
This is meant to provide an alternative to - and probably complete replacement for - using the feature pipeline. Typically the developer would create his own data transformation in a separate function then attach it to the data source as a callable. The benefits are:
- More control over creating the dataset while avoiding the complex feature pipeline approach.
- Easier integration of other tools like scikit-learn, Featuretools, and technical indicator libraries.
- Expanding the community by enabling more users to utilize TensorTrade for their ongoing projects as an R&D tool while keeping their independence (they would touch at the datasest creation and model points only).
- Probably faster and more focused development by completely discarding the pipeline approach and keeping only a simpler version of unique and specialized feature transformations that can not be found elsewhere while avoiding repeating or wrapping functionality that can be easily obtained form other libraries. In that case, transformers would work similar to scikit-learn without consideration to passing results through the pipeline. For example, enhancement #142 wouldn't be required.

**Comment by 123mitnik** [comment]
i fully support this request..the most simple reason for having it is that you can plugin external feats that are not directly related to price transformations. I have plenty of them and there is no easy way to integrate them inside TT. The @YasserHassan proposal will allow easy integration of external tools and features for experimenting and will decouple TT from specific implementation rigidness

**Comment by mwbrulhardt** [comment]
This has been incorporated into the `DataFeed`.
