### ISSUE TITLE
All example .ipynb files and code in the tutorial doesn't run

### ISSUE THREAD

**Issue by jakemanger** [tensortrade-org/tensortrade#144]
I have downloaded all requirements and tensortrade. When I run any of the example scripts or go through the tutorial, I run into the error that some package is missing or incorrect, e.g. DiscreteActions does not exist and wallet_tuples is not in Portfolio (it was changed to wallets). The list goes on.

To reproduce, download tensortrade, install requirements, try any of the example files or the tutorial.

It's quite difficult to understand how this library works without a single working example.

**Comment by YasserHassan** [comment]
The project is currently undergoing many changes. The examples and documentations haven't been updated yet. Hopefully some of these issues will be fixed with the upcoming PR merges. For the time being, try finding more help via Discord discussions.

**Comment by notadamking** [comment]
The examples are being updated this week. Currently, the `setup_environment_tutorial` and `train_and_evaluate` examples are working. The rest will be updated this week.
