### ISSUE TITLE
ImportError: cannot import name 'DiscreteActions'

### ISSUE THREAD

**Issue by 123mitnik** [tensortrade-org/tensortrade#145]
just installed tensortrade. I tried to run some simple code and to see how this lib is working but unfortunately stumbled on the following 

when calling 

```
from tensortrade.actions import DiscreteActions
```

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-7264a5a4d021> in <module>
----> 1 from tensortrade.actions import DiscreteActions
      2 
      3 action_scheme = DiscreteActions(n_actions=20, instrument='BTC')

ImportError: cannot import name 'DiscreteActions'

```

any working example of tensortrade will be appreciated

**Comment by ycchangabriel** [comment]
I have the same issue

**Comment by neahook** [comment]
Same issue here, have searched the internet looking for clues and can't find anything. Also have this error when running the run-tester command:

collected 129 items / 1 errors / 128 selected                                                                          

======================================================== ERRORS ========================================================
____________________________ ERROR collecting tests/tensortrade/exchanges/test_exchange.py _____________________________
ImportError while importing test module '/tests/tensortrade/exchanges/test_exchange.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/tensortrade/exchanges/test_exchange.py:13: in <module>
    from tensortrade.exchanges.simulated import SimulatedExchange, FBMExchange
E   ImportError: cannot import name 'FBMExchange'
=================================================== warnings summary ===================================================
usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15
  /usr/local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

usr/local/lib/python3.6/site-packages/tensorflow/contrib/lite/python/__init__.py:26
  /usr/local/lib/python3.6/site-packages/tensorflow/contrib/lite/python/__init__.py:26: PendingDeprecationWarning: WARNING: TF Lite has moved from tf.contrib.lite to tf.lite. Please update your imports. This will be a breaking error in TensorFlow version 2.0.
    _warnings.warn(WARNING, PendingDeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================= 2 warnings, 1 error in 5.23s =============================================
make: *** [Makefile:8: test] Error 2
make: *** [run-tests] Error 2

**Comment by YasserHassan** [comment]
The tutorial hasn't been updated yet. Try the _new_actions_ notebook or check again after the new PRs are merged.

**Comment by 123mitnik** [comment]
@YasserHassan it is not working either .. I guess we just need to wait

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-d0e6710629aa> in <module>
     37 wallets = [(exchange, USD, 10000), (exchange, BTC, 0)]
     38 
---> 39 portfolio = Portfolio(base_instrument=USD, wallet_tuples=wallets)
     40 
     41 environment = TradingEnvironment(exchange=exchange,

~/anaconda2/envs/py36/lib/python3.6/site-packages/tensortrade/base/component.py in __call__(cls, *args, **kwargs)
     19         instance = cls.__new__(cls, *args, **kwargs)
     20         setattr(instance, 'context', Context(**config))
---> 21         instance.__init__(*args, **kwargs)
     22 
     23         return instance

TypeError: __init__() got an unexpected keyword argument 'wallet_tuples'

```

**Comment by neahook** [comment]
Good things are worth waiting for :-)

**Comment by YasserHassan** [comment]
You can also try finding help via Discord discussions.

**Comment by mg64ve** [comment]
I have same issue

**Comment by mwbrulhardt** [comment]
The DiscreteActions class does not exist anymore.
