### ISSUE TITLE
the error of  strategy.run () return value.

### ISSUE THREAD

**Issue by tendrillion** [tensortrade-org/tensortrade#148]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensortrader) or on the [TensorTrade Discord](https://discord.gg/ZZ7BGWh) #help-desk channel instead of opening a GitHub issue.</em>

**System information**

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04):
- TensorTrade version:0.1.0rc1
- TensorFlow version:1.13.1
- Python version:3.6.7

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
In the dataframe returned by strategy.run(), "step" should be the index。

**Describe the expected behavior**
Actually, "step" is in the column, but not index

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
![图片](https://user-images.githubusercontent.com/33444336/72401943-7c607e80-3788-11ea-86e5-9213ef62818c.png)

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by notadamking** [comment]
Strategies have been removed from the library.
