### ISSUE TITLE
Hierarchical training using multi-agents - Feature Request

### ISSUE THREAD

**Issue by 123mitnik** [tensortrade-org/tensortrade#157]
The implementation of hierarchical training inside TT will be a crucial part of implementing profitable strategies. 

It may be the difference between winning and losing strategy. 

By implementing hierarchical training, the training decisions can be grouped into different levels of granularity (e.g. timeframes based - long/short term, etc..) this way a group of agents can cooperate and create a powerful combination of trading decisions capable of executing profitable strategies.

See, for example, this sample Ray hierarchical training strategy

https://github.com/ray-project/ray/blob/master/rllib/examples/hierarchical_training.py

Also a good reference - https://arxiv.org/pdf/1811.09549.pdf

Points:
4.2 Hierarchical decision making
4.3 Algorithmic, regulatory and computational challenges
5 Hierarchical reinforcement learning scheme

**Comment by 123mitnik** [comment]
no need to implement this from scratch - it is already available in Ray rllib and it is distributed

**Comment by jefferyanderson** [comment]
@123mitnik did this go anywhere?

**Comment by mwbrulhardt** [comment]
This is not within the scope of what the library aims to do. If you want to think about this type of training put try to explore the `ray` library.
