### ISSUE TITLE
Change InvalidOrderQuantity name to match description and add new ones for fractions

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#158]
I suggest renaming `InvalidOrderQuantity` to `InvalidNegativeOrderQuantity` to match its description "_Order sizes must be positive._" and add new `InvalidFractionalOrderQuantity/InvalidNonIntegerOrderQuantity` and `InvalidFractionalQuantity/InvalidNonIntegerQuantity` exceptions for the invalid fraction quantities with fractions for both order and quantity exceptions to be used with such cases.

https://github.com/tensortrade-org/tensortrade/blob/749af2f4a220c40f24abd5ee88138a264b658e44/tensortrade/base/exceptions.py#L60

**Comment by rhamnett** [comment]
I believe this to have been resolved with various commits, feel free to re-open an issue should you require.
