### ISSUE TITLE
ImportError: cannot import name 'StableBaselinesTradingStrategy'

### ISSUE THREAD

**Issue by NetAck-76** [tensortrade-org/tensortrade#160]
Hi,

I've recently start to test tensortrade, and hi start to check how it operate using sample in the GIT repository.
If I try to run the  _"tensortrade/examples/new_actions.ipynb"_ sample I get this error:

from tensortrade.strategies import StableBaselinesTradingStrategy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'StableBaselinesTradingStrategy'
>>> from tensortrade.environments import TradingEnvironment

**System information**

- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorTrade version: 0.1.0rc1
- TensorFlow version: 1.14.0rc1
- Python version: 3.6.9

**Comment by notadamking** [comment]
Removed from library in 0.2.0
