### ISSUE TITLE
Enhancement: Make exchange optional in Wallet

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#165]
I think `exchange` should be optional here. I imagine if I want to use a wallet for a stock like TSLA or GOOG, I would only need the symbol and quantity (and average share price) but not necessarily the exchange.

https://github.com/tensortrade-org/tensortrade/blob/401062089d4235eb844c588b3ff4a841cdc30b43/tensortrade/wallets/wallet.py#L25

**Comment by mwbrulhardt** [comment]
Exchange can not be optional because an instrument can only realistically exist within the context of an exchange. Also the order management system needs the information from the exchange to execute orders and incur transactions on the wallet.

**Comment by YasserHassan** [comment]
If the wallet is used as a component in other projects outside of TensorTrade control or maybe within it but with a custom order management system, the exchange might not be needed. I'll close the issue at this point and it could be reopened if this request is in demand.
