### ISSUE TITLE
Unconfirmed Bug: The example setup_environment_tutorial.ipynb breaks when ran

### ISSUE THREAD

**Issue by CycloneMAO** [tensortrade-org/tensortrade#167]
**Error tracing**
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-127-85400e2daa32> in <module>
      3 env = TradingEnvironment(portfolio=portfolio,
      4     action_scheme='managed-risk',
----> 5     reward_scheme='simple')

E:\anaconda\envs\STA\lib\site-packages\tensortrade\environments\trading_environment.py in __init__(self, portfolio, action_scheme, reward_scheme, feed, window_size, use_internal, **kwargs)
     86         logging.getLogger('tensorflow').disabled = kwargs.get('disable_tensorflow_logger', True)
     87 
---> 88         self.compile()
     89 
     90     def compile(self):

E:\anaconda\envs\STA\lib\site-packages\tensortrade\environments\trading_environment.py in compile(self)
    104         self.feed = self.feed + create_internal_feed(self.portfolio)
    105 
--> 106         initial_obs = self.feed.next()
    107         n_features = len(initial_obs.keys()) if self.use_internal else len(self._external_keys)
    108 

E:\anaconda\envs\STA\lib\site-packages\tensortrade\data\stream\feed.py in next(self)
     83 
     84         for node in self.inputs:
---> 85             self._next(node)
     86 
     87         feed_data = {name: self._data[name] for name in self.names}

E:\anaconda\envs\STA\lib\site-packages\tensortrade\data\stream\feed.py in _next(self, node)
     77             for output_node in node.outbound:
     78 
---> 79                 self._next(output_node)
     80 
     81     def next(self):

E:\anaconda\envs\STA\lib\site-packages\tensortrade\data\stream\feed.py in _next(self, node)
     77             for output_node in node.outbound:
     78 
---> 79                 self._next(output_node)
     80 
     81     def next(self):

E:\anaconda\envs\STA\lib\site-packages\tensortrade\data\stream\feed.py in _next(self, node)
     71 
     72     def _next(self, node: Node):
---> 73         outbound_data = node.next()
     74         if outbound_data:
     75             self._data.update(outbound_data)

E:\anaconda\envs\STA\lib\site-packages\tensortrade\data\stream\node.py in next(self)
    111         self._call_count = 0
    112 
--> 113         data = {self.name: self.forward(self._inbound_data)}
    114         outbound_data = _flatten(data, sep=self._sep) if self.flatten else data
    115         self.propagate(outbound_data)

E:\anaconda\envs\STA\lib\site-packages\tensortrade\data\stream\transform.py in forward(self, inbound_data)
     79     def forward(self, inbound_data):
     80         if not self.key:
---> 81             self.key = list(filter(self.selector, inbound_data.keys()))[0]
     82             self.name = self.key
     83         return inbound_data[self.key]

IndexError: list index out of range
**Describe the current behavior**
self.key = list(filter(self.selector, inbound_data.keys()))[0] will cause index error when the list created is empty, especially happening in train_and_evaluate.ipynb. Further found that this empty list happens when using create_internal_feed(portfolio) in the TradingEnvironment.complie() method. Actually the third node of the created feed is <Node: name=free>, which will trigger the bug above.
Also I feel confused that the complie method will create an internal feed for initializing the env no matter the argument for 'use_internal' is True or False.
**Describe the expected behavior**
First, the bug in the create_internal_feed() should be fixed. Second, the internal_feed method should not be implemented in complie() method when the trading environment is established.
**Code to reproduce the issue**  
from tensortrade.wallets import Wallet, Portfolio
""
portfolio = Portfolio(USD, [
    Wallet(coinbase, 10000 * USD),
    Wallet(coinbase, 10 * BTC),
    Wallet(coinbase, 5 * ETH),
    Wallet(bitstamp, 1000 * USD),
    Wallet(bitstamp, 5 * BTC),
    Wallet(bitstamp, 3 * LTC),
])

from tensortrade.environments import TradingEnvironment

env = TradingEnvironment(
    feed=feed,
    portfolio=portfolio,
    action_scheme='managed-risk',
    reward_scheme='simple',
    window_size=15,
    enable_logger=False
)
""
This is the codes(part) in the example. I have implemented some experiments, using the following codes:
""
from tensortrade.data.internal.helpers import create_internal_feed
from tensortrade.instruments import USD, BTC, ETH, LTC
from tensortrade.wallets import Wallet, Portfolio
portfolio = Portfolio(USD, [
    Wallet(coinbase, 10000 * USD),
    Wallet(coinbase, 10 * BTC),
    Wallet(coinbase, 5 * ETH),
    Wallet(bitstamp, 1000 * USD),
    Wallet(bitstamp, 5 * BTC),
    Wallet(bitstamp, 3 * LTC),
])
new_feed=create_internal_feed(portfolio) 
for i in range(len(new_feed.inputs)):
    print(i)
    new_feed._next(new_feed.inputs[i]) 
""
The above codes will trigger the same bug when i=2(i.e., the third node in new_feed.inputs.
**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by CycloneMAO** [comment]
The following codes define the compile method, which is part of the initialization of the TradingEnvironment class within the package's source code.
def compile(self):
        """
        Sets the observation space and the action space of the environment.
        Creates the internal feed and sets initialization for different components.
        """
        for component in [self._broker, self.portfolio, self.action_scheme, self.reward_scheme]:
            component.clock = self.clock

        self.action_scheme.set_pairs(exchange_pairs=self.portfolio.exchange_pairs)
        self.action_space = Discrete(len(self.action_scheme))

        if not self.feed:
            self.feed = create_internal_feed(self.portfolio)

        self.feed = self.feed + create_internal_feed(self.portfolio)

        initial_obs = self.feed.next()
        n_features = len(initial_obs.keys()) if self.use_internal else len(self._external_keys)

        self.observation_space = Box(
            low=self._observation_lows,
            high=self._observation_highs,
            shape=(self.window_size, n_features),
            dtype=self._observation_dtype
        )

        self.feed.reset()

**Comment by CycloneMAO** [comment]
Sorry, the node which triggers this bug is the second node: <Node: name=USD-ETH>

**Comment by notadamking** [comment]
The example is currently working with the latest version of the repo. Make sure you have installed from the Github source:

`pip install git+https://github.com/notadamking/tensortrade.git -U`
