### ISSUE TITLE
Reward ratio calculation relativity

### ISSUE THREAD

**Issue by diazagasatya** [tensortrade-org/tensortrade#169]
For Reward calculation shouldn't we use pct_change() instead of diff() of the net_worth column? I'm referring to the get_reward() function in the risk_adjusted_returns.py file.

For instance, if we are using diff(), a change from a net worth of 9000 -> 9100 will be measured the same as a change in the net worth of 1,000,000 -> 1,000,100. 

Whereas if we use pct_change() the reward will be proportional to the overall net worth of the asset, giving more relativity into the overall reward ratio.

**Comment by mwbrulhardt** [comment]
Merged the PR.
