### ISSUE TITLE
Feature Request: Add commission type to ExchangeOptions

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#171]
This is intended to accommodate the different commission types, per trade and per share, and consequently change the commission calculation method.

And while at it, shouldn't the commission as a whole and trade price/size be associated to Broker not Exchange?

**Comment by notadamking** [comment]
@YasserHassan I look forward to your PR. The commission is associated with the exchange, as the `Broker` is only used internally, and does not actually execute trades on the exchange. This is done by a specific exchange `execution_service`.

**Comment by YasserHassan** [comment]
@notadamking I'm working on it but I need some clarifications to confirm my understanding:
https://github.com/tensortrade-org/tensortrade/blob/0e94705439933b2d85eefb5816c229ab99b728fb/tensortrade/exchanges/exchange.py#L34-L37
- `min/max_trade_size` refers to the number of shares per trade?
- `min/max_trade_price` refers to the single share price? (not total $ value of a single trade)

https://github.com/tensortrade-org/tensortrade/blob/0e94705439933b2d85eefb5816c229ab99b728fb/tensortrade/exchanges/services/execution/simulated.py#L47
This is actually the same as `quote_size = order.price / price`, am I seeing that right? Should also be converted to int as order sizes are integers only.

**Comment by carlogrisetti** [comment]
@YasserHassan I suppose this died a lot of time ago. Are you still interested in implementing this PR ?
Any use case I explored had a commission based on a percentage of the total value of the trade, so the current implementation seems to be enough for me, but that's only my point of view.

Thanks!

**Comment by carlogrisetti** [comment]
Closing as stale. Please comment\reopen if further details arise
