### ISSUE TITLE
Question: Balances remain in locked balances when after trade has been executed

### ISSUE THREAD

**Issue by MarcusDoubleYou** [tensortrade-org/tensortrade#172]
this is something I noticed during training. That balances will remain in locked_balances when buy -> sell is executed.

Here is a simple test to illustrate the issue.
```
def test_runs_with__buy_sell_error():
    df = pd.read_csv("tests/data/input/coinbase_(BTC,ETH)USD_d.csv").tail(100)
    df = df.rename({"Unnamed: 0": "date"}, axis=1)
    df = df.set_index("date")

    ex1 = Exchange("coinbase", service=execute_order)(Stream("USD-BTC", list(df['BTC:close'])))

    portfolio = Portfolio(USD, [
        Wallet(ex1, 10000 * USD),
        Wallet(ex1, 0 * BTC)
    ])

    coinbase_btc = df.loc[:, [name.startswith("BTC") for name in df.columns]]

    nodes = []
    with Module("coinbase") as coinbase:
        for name in coinbase_btc.columns:
            nodes += [Stream(name, list(coinbase_btc[name]))]

    feed = DataFeed()(coinbase)

    action_scheme = DynamicOrders(
        trade_sizes=[1.0],
        trade_type=TradeType.MARKET
    )
    reward_scheme = SimpleProfit()

    env = TradingEnvironment(
        portfolio=portfolio,
        action_scheme=action_scheme,
        reward_scheme=reward_scheme,
        feed=feed,
        window_size=5
    )

    env.reset()
    holding_action = 1
    # Buy USD/BTC use all available funds
    buy_all_action = 2
    # Sell BTC/USD use all available funds
    sell_all_action = 3

    env.step(buy_all_action)
    assert len(env.broker.executed) == 1

    env.step(sell_all_action)
    assert len(env.broker.executed) == 2
     # balances will stay in locked_balances and not return in to balances

    env.step(buy_all_action)
    # order will get get executed
    # assert len(env.broker.executed) == 3
```

Prerequisite: 
This requires a fix to the class DynamicOrders(ActionScheme):
[...]
price = exchange.quote_price(pair)
instead of 
price = exchange.quote_price(instrument)
[...]

Maybe its a issue that the order service needs to be adjusted or the default order server is not working with the action scheme? However, I would expect to the traded funds to back into the balances when the env shows the trades as executed and not in locked balances

**Comment by bwcknr** [comment]
I've already seen that behaviour.

Since the change to support multiple exchanges (and the symptomatic fix in broker.update) this happens.

Since actions are taken on pair and exchange, the portfolio takes the amount off the wallet on that exchange. But the broker and order executions do not respect that.

The broker currently does not know about that and just executes orders on exchanges that trade the orders pair and fulfil the orders criteria.

The right fix would be to lock orders created by actions to exchanges and let them be executed on that exchange exclusively.

I would handle that issue, but got plenty of payed work to do :/

**Comment by 123mitnik** [comment]
yes ..the order server is not working and the agent is not learning. once a trade is made the balance is locked and there are no more trades. 

Also, the 'Order:'  is  'None'

**Comment by MarcusDoubleYou** [comment]
@123mitnik @bwcknr do you know by any chance if the order service (and more broadly how orders are executed and balances are locked unlocked maintained) is still WIP as part of all the recent changes or would it make sense to look into it?

**Comment by 123mitnik** [comment]
@MarcusDoubleYou I strongly believe that this is not WIP... but let me ask your question in discord just in case

**Comment by bwcknr** [comment]
@MarcusDoubleYou I am just contributing my points and am excited about the efforts. I am not involved in planning.

But from my point of view the latest efforts are about getting the data feed right.

**Comment by notadamking** [comment]
Can you check if this is still happening after the latest commit?

**Comment by 123mitnik** [comment]
@notadamking still the same .. just installed from the master and the balance is still locked after the first trade. the agent is still not learning

**Comment by 123mitnik** [comment]
there is something fishy about the order's execution.. there was some issue when logging into the terminal and it displayed that the observation is 1x10 .. now in the log I see that this data is not displayed .. So I printed and the data seems to be correct; at least in the first look.

features: [11209 rows x 325 columns]
agent observations shape: (6, 334)

this will need confirmation from someone

**Comment by 123mitnik** [comment]
the balances are locked after the initial trades. I did additional testing and left TT to execute for 2478 steps. The account advanced to 100%  profit (from the initial trades).. but no trade was closed and the agent is not trading 
``` P/L:         2.142912898249354
Reward (2478): 0.035180304492160065
Performance:       coinbase:/USD-BTC  coinbase:/USD:/free  coinbase:/USD:/locked  coinbase:/USD:/total  coinbase:/BTC:/free  coinbase:/BTC:/locked  coinbase:/BTC:/total  coinbase:/BTC:/worth    net_worth base_symbol
step
2478            5296.97             0.007927               7.928144              7.936071             0.000553               0.200226              0.200779           1063.520378  1071.456449         USD```

**Comment by notadamking** [comment]
This is the case if the balance is locked in a trade w/ a criteria that has not yet been met.

The fix is to add a `duration` to your orders, to ensure they get cancelled if not completed after `duration` steps.

**Comment by MarcusDoubleYou** [comment]
@notadamking could this be caused because by default no criteria is defined for the DynamicOrders(ActionScheme). Hence, no criteria can be met? What would be the expected behavior if no criteria are given? Since those are market orders I would expect all orders simply to be executed and balance are unlocked, right?

**Comment by 123mitnik** [comment]
@notadamking Yes Adam, this is the problem I tested it and when setting the duration - the problem is gone .. there must be a default value for the duration
