### ISSUE TITLE
Unconfirmed Bug: Unit test returns different calculations than expected in RiskAdjustedReturns

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#173]
The returns calculation is different in the class method and its corresponding test after commit 9fd7269. It does not break the test though.

https://github.com/tensortrade-org/tensortrade/blob/9fd7269f64f547a3e1cd713db03733660adc05df/tensortrade/rewards/risk_adjusted_returns.py#L70

https://github.com/tensortrade-org/tensortrade/blob/9fd7269f64f547a3e1cd713db03733660adc05df/tests/tensortrade/unit/rewards/test_risk_adjusted_returns.py#L34

**Comment by notadamking** [comment]
Nice catch @YasserHassan. Care to submit a PR to fix this issue?

**Comment by YasserHassan** [comment]
@notadamking done. Please check.

**Comment by carlogrisetti** [comment]
This should be already merged completely. Closing due to being left open.
If there is still something missing, just comment again on this issue.

Thanks!
