### ISSUE TITLE
Example Request: Portfolio-independent, single-instrument tutorial (i.e. `use_internal=False` example) 

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#175]
The current implementations incorporate portfolio information into agents' training as part of the environment observation data (and hence is required later in live operation). This approach is very specific and I believe it would require frequent retraining to adopt to small changes that are likely to occur frequently for fine tuning such as changing `trade_sizes` in `ManagedRiskOrders`.

My suggestion is to create an implementation (or tutorial if it doesn't require changes in the codebase) that depends only on the market (exchange) data. This aims to answer the question "is it best now to buy, sell, or do nothing?". The actual fund and order management part (order size calculations, order type, real or simulated, ...etc) would be moved out of the agent's scope to the developer's own functionality to decide what to do with the received signals, whether using TensorTrade or other functionality.

I imagine that can be done by calculating the reward based on the instrument price difference between the buy and sell points.

**Comment by YasserHassan** [comment]
The above suggestion aims to generate buy/sell signals at major price change points on the chart regardless of the actual position.

Another variation is adding the current position status as a flag (not actual position size) and P/L to the model inputs. Position status could be:
- Holding / Not Holding (True/False) for full position buy/sell trading scenarios. The possible outputs are: Buy, Sell, Do Nothing.
- Holding / Not Holding / Partial Position for the partial buy/sell scenarios. The possible outputs are: Buy / Sell (all) / Add to Position / Decrease Position.

**Comment by 123mitnik** [comment]
yes .. the agent should not observe actual price .. or other specific levels .. Instead, it must be aware of relative or binary data of the targeted values. this way we can decouple the agents from specific levels and will avoid  re-training or dangerous trade situations

**Comment by YasserHassan** [comment]
@123mitnik yes, price difference - if included - should be relative. Cumulative percentage change may even be better. Either way, that change should be part of the reward calculation.

**Comment by YasserHassan** [comment]
I'm reopening this as a reminder of the example.

**Comment by YasserHassan** [comment]
I'm reopening this as a reminder of the example.

**Comment by mwbrulhardt** [comment]
This is possible now because it is no longer required that the portfolio needs to be included into the observation space. That can be done by the user and not internally.
