### ISSUE TITLE
Example Request: Save and restore agent from checkpoint

### ISSUE THREAD

**Issue by 123mitnik** [tensortrade-org/tensortrade#176]
inside the train_and_evaluate example, you can see ``` agent.train(n_steps=200, save_path="examples/agents/") ``` but no model has been stored to the fodder .

Also, an example of how to restore it from the saved model is missing.

It will be good to show inside the example the two cases once this is fixed:
1. case one - how to load the saved model and continue training 
2. case two - how to load a saved model and use it in production - only for prediction

**Comment by notadamking** [comment]
This is a good idea. These examples will be added ASAP.

**Comment by Debra1761** [comment]
Can I work on this issue? I have a  working tf-agents implementation of DQN agent with the checkpointing functionality. Would it be a good design choice?

**Comment by ramoslin02** [comment]
> This is a good idea. These examples will be added ASAP.

Couldn't wait for this function, especially the the live trading.

**Comment by liubarnabas** [comment]
Where is the example?

**Comment by orthosku** [comment]
has this been completed? would love to see it!
