### ISSUE TITLE
Example Request: Add evaluation step to train_and_evaluate notebook

### ISSUE THREAD

**Issue by 123mitnik** [tensortrade-org/tensortrade#177]
inside train_and_evaluate - the evaluation step is missing 

Also, it would be good to include functionality to split the data on - train/test -- this way we will be able to perform a true evaluation on unseen data

**Comment by notadamking** [comment]
Good idea. I would love to see an implementation if you had one in mind!

**Comment by ozcelikkale** [comment]
could you handle the issue?? @123mitnik @notadamking

**Comment by AlexQuant62** [comment]
as an example of division of dataset to training/cv/testing see here:
https://github.com/sam31415/timeseriescv

**Comment by carlogrisetti** [comment]
This also covers training and evaluation. It's the most recent example.
https://www.tensortrade.org/en/latest/examples/train_and_evaluate_using_ray.html
