### ISSUE TITLE
Bug: Inconsistent dictionary key arrangement in TradingEnvironment feed 

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#179]
The key arrangement of the TradingEnvironment feed attribute changes from one instance to another. Duplication steps:
1. Open `train_and_evaluate.ipynb` form examples.
2. Run till the cell `env.feed.next()`.
3. Notice the generated dictionary key arrangement.
4. Go up to the previous code cell (containing `env = TradingEnvironment(...)`) and run down to `env.feed.next()` again.
5. Compare the resultant dictionary key arrangement to step 3.

**Comment by mwbrulhardt** [comment]
Merged PR.
