### ISSUE TITLE
Enhancement: Make TradingEnvironment feed creation configurable using optional callable

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#182]
Currently, the internal data feed is part of the TradingEnvironment feed. It is created in way that doesn't allow for changing the way the position/portfolio status is represented in the full feed. This is something developers may need to do. For example, to train the model based on the change in value of a purchased asset regardless of the other portfolio factors (issue #175).

So I suggest making the internal data creation function configurable via an optional constructor parameter that is used instead of `create_internal_feed()` if provided.

Better yet, make the whole TradingEnvironment feed creation configurable via an optional callable that takes the portfolio and returns the full feed created in the way the developer wants.

**Comment by mwbrulhardt** [comment]
This is already possible with the current setup. You do not have to use the internal data feed. You can write `use_internal=False` in the environment constructor and incorporate the portfolio, the way you see fit, into the data feed you provide for environment.

**Comment by notadamking** [comment]
@mwbrulhardt, this is already possible using `use_internal=False` and a custom data feed.

**Comment by 123mitnik** [comment]
when I write ``use_internal=False``` inside the TradingEnvironment like this:

```
env = TradingEnvironment(
    feed=feed,
    portfolio=portfolio,
    use_internal=False,
    action_scheme=action_scheme,
    reward_scheme='risk-adjusted',
    window_size=24,
    enable_logger=True
)
```
i get the following error
``` [1]    67842 floating point exception ```
