### ISSUE TITLE
It is still available to use tensorforce and stable_baselines ?

### ISSUE THREAD

**Issue by giranntu** [tensortrade-org/tensortrade#192]
As we are using the TF 2.1.0 in TensorTrade current build. 
The OpenAI baselines (stable baselines) are not supporting in TF2.0 env. 
which we should find out the way to use it. 
Or if I follow the tutorial in http://www.tensortrade.org/en/latest/agents/stable_baselines.html

There is an error. 
Please guide how to use tensorforce and baselines.

**Comment by giranntu** [comment]
I tried many APIs like MultiDiscreteActions and it does not exist in the current build.
I guess the documents need to be updated.

**Comment by YasserHassan** [comment]
The documents haven't been updated yet. You can join Discord for help.

**Comment by mwbrulhardt** [comment]
The documentation must be updated because these are no longer features in the library.
