### ISSUE TITLE
Parallel DQN Agent not working.

### ISSUE THREAD

**Issue by giranntu** [tensortrade-org/tensortrade#193]
When I trying to train the Parallel DQN Agent, it did create n worker, but as I plot the portfolio, it doesn't do anything for trading, so it might be the Parallel DQN Agent lib not build in the right way...?

**Comment by giranntu** [comment]
Would like to know the new release contains any update of this?

**Comment by segatrade** [comment]
> Not in scope anymore, since agents are mainly offloaded to ray and\or other frameworks. Thanks anyway so much for the help\interest

Probably it's good to delete them from repo or put some notification about it
