### ISSUE TITLE
Feature Request: Add time stamp to saved model file name and use shorter id

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#197]
Currently the saved model file names are something like `policy_network__4b593b4e-7548-4f5d-bc71-3a4ee137ef03.hdf5`. Adding a timestamp like `MMDDYY_HHMMSS` (e.g. `20200211_203525`) in the middle and using the first 7 characters of the id like the short GitHub commit identifiers (e.g. `policy_network_20200211_203525_4b593b4.hdf5`) can make dealing with the saved models easier.

**Comment by carlogrisetti** [comment]
Fixed with #219 
Thanks for reporting this
