### ISSUE TITLE
Tutorial Issues: tensortrade.strategies folder doesn't exist

### ISSUE THREAD

**Issue by jasonfiacco** [tensortrade-org/tensortrade#200]
Many code blocks from both the documentation and the Medium page tutorial don't seem to work properly. For example, one line is "from tensortrade.strategies import TensorforceTradingStrategy, StableBaselinesTradingStrategy" but it seems that there is no tensortrade.strategies folder/module any longer. Is there some more recent tutorial that can be used?

Using Tensorflow version 1.13.1.

**Comment by YasserHassan** [comment]
Documentation hasn't been updated yet. Better follow the examples, read the code, and join Discord for help. And use TensorFlow 2.1.

**Comment by spacewalkingninja** [comment]
> Documentation hasn't been updated yet. Better follow the examples, read the code, and join Discord for help. And use TensorFlow 2.1.

Hello!
I will give an example here as how I put it working in Google collab, PRIOR to your new rendering solution. 

`from google.colab import drive
drive.mount('/content/gdrive')
`
Then we go to
`
cd '/content/gdrive/My Drive/.../tensortrade-master'
`
and install:
`
!python3 -m pip install -e . -U
`

Instruct collab were going to use TF2
`
%tensorflow_version 2.x
`

Here is a new DataFetch mechanism, just got it working
IMPORTANT> It is Binance specific!
`
import ssl
import pandas as pd

import numpy as np
import math
import threading
import requests
import ast
import time
import os
import csv
from datetime import datetime

ssl._create_default_https_context = ssl._create_unverified_context # Only used if pandas gives a SSLError


def deleteThefile(filepath):
    try:
      os.remove(filepath)
    except IOError:
      print("File not created")

def getOhlcData(symbol, lmt):
    datas = []

    #get the rest
    e = threading.Event()
    e.wait(1)
    i = 0
    imax = lmt
    while i < imax:
        if i < 1:
            print("pullin data...0/"+str(imax))
            conn = requests.get("https://api.binance.com/api/v3/klines?symbol={0}USDT&interval=1m&limit=1000".format(symbol))
        if i > 0:
            print("pullin data..."+str(i)+"/"+str(imax))
            #print(startTime)
            conn = requests.get("https://api.binance.com/api/v3/klines?symbol={0}USDT&interval=1m&endTime={1}&limit=1000".format(symbol, startTime))
        i = i + 1
        res = conn.content
        data = res.decode()
        data = ast.literal_eval(data)
        limit = len(data)
        datas.insert(0, data)

        startTime = data[0][0]
        e.wait(1)

    deleteThefile('./data/{0}.csv'.format(symbol))
    formatCSVFile(symbol)
    while bool(datas):
        data_to_csv(datas.pop(), symbol)  #write the oldest first 

    #return the filepath to the  data file
    return './data/{0}.csv'.format(symbol)

def data_to_csv(data, fileName):
    with open("./data/{0}.csv".format(fileName), "a+") as my_csv:
        csvWriter = csv.writer(my_csv, delimiter=',')
        csvWriter.writerows(data)

def formatCSVFile(symbol):
    string = '"Date","open","high","low","close","volume_' + str(symbol) + '","close_time","Volume USD","no_tr","ig1","ig2","ig3"\r\n'
    f = open("./data/{0}.csv".format(symbol), "a+")
    f.write(string)
    f.close()

def fetch(symbol, lmt):
    filename = getOhlcData(symbol, lmt)
    print(filename)
    volume_column = "Volume {}".format(symbol)
    new_volume_column = "Volume_{}".format(symbol)
    df = pd.read_csv(filename, skiprows=0)
    
    df = df[::-1]
    df = df.drop(["no_tr"], axis=1)
    df = df.drop(["close_time"], axis=1)
    df = df.drop(["ig1"], axis=1)
    df = df.drop(["ig2"], axis=1)
    df = df.drop(["ig3"], axis=1)
    df = df.rename({"Volume USD": "volume", volume_column: new_volume_column}, axis=1)
    df = df.set_index("Date")
    df.columns = [symbol + ":" + name.lower() for name in df.columns]
    df.reset_index(inplace=True, drop=True)
                     
    return df

df = fetch("LTC", 1)
print(df)
print(df.columns)
`

Setup trading environment 

`
from tensortrade.exchanges import Exchange
from tensortrade.exchanges.services.execution.simulated import execute_order
from tensortrade.data import Stream, DataFeed, Module
from tensortrade.instruments import USD, BTC, ETH, LTC
from tensortrade.wallets import Wallet, Portfolio
from tensortrade.environments import TradingEnvironment

coinbase_data = pd.concat([
    fetch("BTC", 100),
    fetch("LTC", 100),
    fetch("ETH", 100)
], axis=1)

coinbase = Exchange("coinbase", service=execute_order)(
    Stream("USD-BTC", list(coinbase_data['BTC:close'])),
    Stream("USD-LTC", list(coinbase_data['LTC:close'])),
    Stream("USD-ETH", list(coinbase_data['ETH:close']))
)

coinbase_btc = coinbase_data.loc[:, [name.startswith("BTC") for name in coinbase_data.columns]]

with Module("coinbase") as coinbase_ns:
    nodes = [Stream(name, list(coinbase_data[name])) for name in coinbase_data.columns]

feed = DataFeed([coinbase_ns])

portfolio = Portfolio(USD, [
    Wallet(coinbase, 100 * USD),
    Wallet(coinbase, 0 * BTC),
    Wallet(coinbase, 0 * LTC),
    Wallet(coinbase, 0 * ETH),
])

env = TradingEnvironment(
    feed=feed,
    portfolio=portfolio,
    action_scheme='managed-risk', #managed-risk | simple
    reward_scheme='risk-adjusted', #risk-adjusted | simple
    window_size=20
)
`
Example Data Feed Observation
`
env.feed.next()
`
Setup and Train DQN Agent

`
from tensortrade.agents import DQNAgent

agent = DQNAgent(env)

`
#agent.train(n_steps=1000, save_every=1, save_path="examples/agents/")
agent.train(n_episodes=5, save_every=1, save_path="examples/agents/")
`
Then we have the performance:
`
%matplotlib inline

portfolio.performance.plot()
`

`
portfolio.performance.net_worth.plot()
`

Setup and Train A2C Agent

`
from tensortrade.agents import A2CAgent

agent = A2CAgent(env)

#same here we can use episodes or steps
agent.train(n_episodes=5, save_path="examples/agents/")
`
Then we have the performance:
`
portfolio.performance.plot()
`

`
portfolio.performance.net_worth.plot()
`

Setup and Train Parallel DQN Agent (UNTESTED BY ME!)
`
from tensortrade.agents import ParallelDQNAgent

def create_env():
    feed = DataFeed([coinbase_ns])

    portfolio = Portfolio(USD, [
        Wallet(coinbase, 10000 * USD),
        Wallet(coinbase, 10 * BTC),
        Wallet(coinbase, 5 * ETH),
    ])
    
    env = TradingEnvironment(
        feed=feed,
        portfolio=portfolio,
        action_scheme='managed-risk',
        reward_scheme='risk-adjusted',
        window_size=20
    )
    
    return env

agent = ParallelDQNAgent(create_env)

agent.train(n_envs=4, n_steps=200, save_path="examples/agents/")
`

Then we have the performance:
`
portfolio.performance.plot()
`

`
portfolio.performance.net_worth.plot()
`

Now I will ask some questions:
a) how do we save the trained model? haven't really researched into this, maybe will today

b) to get it to observe our own environment after training, what should we do? 
My guess so far is hacky, but in the lines of:
`
btc_price = Stream("USD-BTC", [9200, 9212, 9400, 9100, 9300, 9100, 9300, 9100, 9300, 9000, 9300, 9100, 9300, 9100, 9300, 9100, 9300, 9100, 9300, 9100, 9300])
eth_price = Stream("USD-ETH", [200, 212, 400, 100, 1300, 100, 1300, 100, 1300, 100, 1300, 100, 1300, 100, 1300, 100, 1300, 100, 1300, 100, 1300])

exchange = Exchange("coinbase", service=execute_order)(btc_price, eth_price)

env.feed = DataFeed()(exchange)
print (env.feed)
`
and then we say that
`
    done = False
    obs = env
    while not done:

        action = env.action_space.sample()
        order = env.action_scheme.get_order(action, portfolio)
        #print(action)
        if order:
          print(order)
        #print (order)
        obs, reward, done, info = env.step(action)
`
So can you or @notadamking give us some in-depth explanation?
