### ISSUE TITLE
price_history 'NoneType' object has no attribute 'index'

### ISSUE THREAD

**Issue by jonatrey** [tensortrade-org/tensortrade#205]
whenever running the vanilla train_and_evaluate.ipynb - the final step of the training is the render the output and it's trying to access self._price_history.index  (environments/trading_environment.py) which is of type "NoneType".

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-11537aa2bc84> in <module>
      3 agent = DQNAgent(env)
      4 
----> 5 agent.train(n_steps=200, save_path="examples/agents/", render_interval=None)

/tensortrade/agents/dqn_agent.py in train(self, n_steps, n_episodes, save_every, save_path, callback, **kwargs)
    182                 self.save(save_path, episode=episode)
    183 
--> 184             self.env.render(episode)  # render final state at episode end
    185 
    186             episode += 1

/tensortrade/environments/trading_environment.py in render(self, episode, mode)
    308                             step=current_step,
    309                             max_steps=self._max_steps,
--> 310                             price_history=self._price_history[self._price_history.index < current_step],
    311                             net_worth=self._portfolio.performance.net_worth,
    312                             performance=self._portfolio.performance.drop(columns=['base_symbol']),

**Comment by YasserHassan** [comment]
A fix has been submitted in a PR.

**Comment by YasserHassan** [comment]
Meanwhile, as a turnaround, provide price history data as shown in the renderers example.

**Comment by YasserHassan** [comment]
Fixed in #204.

**Comment by jonatrey** [comment]
Thanks
