### ISSUE TITLE
Multiple Price Histories for Plotly Renderer

### ISSUE THREAD

**Issue by tarasivashchuk** [tensortrade-org/tensortrade#215]
Hi,

I was wondering if there is some way to display multiple price histories for environments with more than one pair? Currently when I pass a list of price histories I get the following error:

```
Traceback (most recent call last):
  File "/Users/**/trade.py", line 108, in <module>
    agent.train(n_episodes=3, n_steps=200)
  File "/Users/**/.venv/src/tensortrade/tensortrade/agents/dqn_agent.py", line 185, in train
    self.env.render(episode)  # render final state at episode end if not rendered earlier
  File "/Users/**/.venv/src/tensortrade/tensortrade/environments/trading_environment.py", line 306, in render
    price_history = None if self._price_history is None else self._price_history[self._price_history.index < current_step]
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
```

Here is how I am building the price_histories:

```
def get_price_history(data, symbol):
    # history = dataset.loc[:, [name.startswith(symbol) for name in dataset.columns]]
    history = fetch(symbol, rename=False)
    print(history.columns)
    # history.drop(columns=["dividend", "split_coefficient", "close"], inplace=True)
    history.columns = [
            col for col in ["datetime", "open", "high", "low", "close", "volume"]
    ]
    history.reset_index()
    return history


price_histories = [get_price_history(dataset, symbol) for symbol in SYMBOLS]

```

And then I pass the list directly. If I pass only one element in the list, it works correctly, however, the render displays the buy and sell signals for the other Instruments but without the price candlestick.

I am thinking I can just modify the class myself to fix this and then submit a pull request - I already looked at it and it's not complicated or anything, but figured I'd ask about it first.

Thanks!

**Comment by tarasivashchuk** [comment]
Ok, I looked through the code and the other branches and I'm pretty sure this just doesn't work right now, so I will just implement myself and submit a pull request. Is there a preferred way for me to do this? I was thinking of just allowing to pass DataFrames with multiple OHLC columns for multiple instruments?

**Comment by YasserHassan** [comment]
@tarasivashchuk this issue is a duplicate of #205 and was fixed in #204. Have you updated your version form master? If it persists, a turnaround at the moment is to provide any price history to the environment even if you won't use it.

Currently this is a single instrument chart. Drawing charts of all portfolio positions would be a good enhancement. I see it better implemented as multiple separate stacked charts. Keep in mind that such chart would be very slow to render during episode (every n steps) so it would be better to render at episode ends only.

**Comment by tarasivashchuk** [comment]
@YasserHassan I will implement plotting multiple positions, and let you choose which ones also. Will keep you posted.

**Comment by carlogrisetti** [comment]
@tarasivashchuk have you done any progress in regards to this? Might this be an obsolete issue with something already merged in?

Thanks

**Comment by carlogrisetti** [comment]
Closing due to being stale. If there is any progress, just comment here. Thanks!
