### ISSUE TITLE
Display Plotly in Dash Application?

### ISSUE THREAD

**Issue by tarasivashchuk** [tensortrade-org/tensortrade#216]
Is there anyway to currently do this? I mean in a way that includes taking input from Dash callbacks?

**Comment by YasserHassan** [comment]
The current chart does not support that. What is the use case you'd need that for?

**Comment by tarasivashchuk** [comment]
Displaying the results in a Dash application? Preferably live. It'd be cool to watch the agent in this way as it trains or as it runs live. @YasserHassan

**Comment by YasserHassan** [comment]
It would seem like fun in the beginning but once you go into serious training with hundreds or thousands of episodes, you'll find it counter productive. Not only you'll lose interest after a while but also that rendering time would accumulate to delay your overall training time tremendously. Also once you go into parallel training you'll need a cumbersome setup to do that. Practically, you better have episode-end charts rendered to disk every 20 or even 50 episodes. In between, rely on other metrics for better overall experience.

**Comment by spacewalkingninja** [comment]
> It would seem like fun in the beginning but once you go into serious training with hundreds or thousands of episodes, you'll find it counter productive. Not only you'll lose interest after a while but also that rendering time would accumulate to delay your overall training time tremendously. Also once you go into parallel training you'll need a cumbersome setup to do that. Practically, you better have episode-end charts rendered to disk every 20 or even 50 episodes. In between, rely on other metrics for better overall experience.

Hi! Got any models already trained on a good setup that you could share? Based on your answer, that's what you've been doing.....

**Comment by mitcheccles** [comment]
@tarasivashchuk  @spacewalkingninja - I get the need to display the chart in a dash app, even if only for debug purposes. It is possible to do, checkout my repo: https://github.com/mitcheccles/tensortrade_dashboard

**Comment by rhamnett** [comment]
This is not something we have plans to do at present. If you wish to supply a PR then please feel free.
