### ISSUE TITLE
Support Ally Invest?

### ISSUE THREAD

**Issue by OneCricketeer** [tensortrade-org/tensortrade#217]
**Feature Request**

https://invest.ally.com

Doesn't appear there is a proper Python SDK, but it _seems_ there is just an OAuth client used to do things... Ruby should be a straightorward translation - https://www.ally.com/api/invest/documentation/ruby/

**Comment by kodiakcrypto** [comment]
More work on the fundamentals is currently needed.

**Comment by cricket007** [comment]
Gotcha. I assume that progress [is being tracked](https://github.com/tensortrade-org/tensortrade/projects)?
