### ISSUE TITLE
Feature Request: ActionStrategy and InstrumentExchange for Futures trading

### ISSUE THREAD

**Issue by ruifeng96150** [tensortrade-org/tensortrade#22]
I am glad to meet a so great project.  when I do some test. I find some new requirements.

1.  I want to use this project for Future and I find that discrete_action_strategy is not support for shorting.  So it's possible to add more type of action strategy in the future? and what's more, the exchange may need  update.
2. For TradeType, I think the limit or market order type should be config as a env parameter.  Such agent action would be simple to create.
3. For actions, the system defined as following, can we make it more simpler? just let 1=buy,2=sell,0=hold? and for the trade amounts, can be add by next signal. (up limit to max_amounts set by user)
```
For example, 1 = LIMIT_BUY|0.25, 2 = MARKET_BUY|0.25, 6 = LIMIT_BUY|0.5, 7 = MARKET_BUY|0.5, etc.
```
Thanks in advance.

**Comment by notadamking** [comment]
@ruifeng96150 would you be interested in implementing these features for some $ETH?

**Comment by ramoslin02** [comment]
Can we implement a switch for trading spot or futures? users just turn on the switch to True for trading Futures and False for spot.

**Comment by ramoslin02** [comment]
> I am glad to meet a so great project. when I do some test. I find some new requirements.
> 
> 1. I want to use this project for Future and I find that discrete_action_strategy is not support for shorting.  So it's possible to add more type of action strategy in the future? and what's more, the exchange may need  update.
> 2. For TradeType, I think the limit or market order type should be config as a env parameter.  Such agent action would be simple to create.
> 3. For actions, the system defined as following, can we make it more simpler? just let 1=buy,2=sell,0=hold? and for the trade amounts, can be add by next signal. (up limit to max_amounts set by user)
> 
> ```
> For example, 1 = LIMIT_BUY|0.25, 2 = MARKET_BUY|0.25, 6 = LIMIT_BUY|0.5, 7 = MARKET_BUY|0.5, etc.
> ```
> 
> Thanks in advance.

This is a good idea, while trading the amount can by send by other signal, or just trading with the fixed amount. Or like the example like this:
> 1 = LONG, 2 = SHORT, 3 = SELL, 4 = COVER, 0 = HOLD or do nothing.

**Comment by elnazsn1988** [comment]
Has this been implemeted a of yet? am interested in same - limit order book trades @notadamking

**Comment by mwbrulhardt** [comment]
Not relevant to current library state anymore.
