### ISSUE TITLE
REQUEST: Release money making models you trained

### ISSUE THREAD

**Issue by spacewalkingninja** [tensortrade-org/tensortrade#224]
No there aren't any pre-trained models.

_Originally posted by @mwbrulhardt in https://github.com/tensortrade-org/tensortrade/issues/151#issuecomment-618475150_

There is obviously an issue that mwbrulhardt did not understand: WE NEED THE MODELS!

REQUEST: Release them for free ASAP!
Thanks!

**Comment by notadamking** [comment]
Sure! While we're at it, you should send me your BTC address so I can send you some free money as well. ;)
