### ISSUE TITLE
Suggestion - integrate Creme for online learning

### ISSUE THREAD

**Issue by magick93** [tensortrade-org/tensortrade#225]
Continual learning, sometimes called online learning (google that if you want to find everything but how to continually learning using RL) could be very useful.

Creme is for In**creme**ntal learning, is where models can update themselves.

Please see https://github.com/creme-ml/creme

I dont know if this would be of benefit to Tensortrade, but thought its worth suggesting and opening the discussion.

**Comment by mwbrulhardt** [comment]
Nice idea! You should bring it up on the `suggestions` channel on the Discord for people to discuss.
