### ISSUE TITLE
ModuleNotFoundError: No module named 'tensortrade.exchange'

### ISSUE THREAD

**Issue by nott0** [tensortrade-org/tensortrade#227]
I have a problem with installing the latest tensortrade. When I run the example as written in the tutorial, I faced with this problem

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from tensortrade.exchanges.simulated import SimulatedExchange
ModuleNotFoundError: No module named 'tensortrade.exchanges.simulated'
```
I tried install by pip command as suggest in Medium, also the https://www.tensortrade.org/ and also directly from git repository, but all result the same (without the module) 

Anyone have any idea?

**Comment by lymzzu** [comment]
I also have this problem.

**Comment by quantwin** [comment]
It seems that  exchanges is not complete.

Or some installation error happened, the  environment is not set up correctly.

Try to create a simulated.py file in ..\site-packages\tensortrade\exchanges,

`
from typing import Callable, Union
from decimal import Decimal

from tensortrade.base import Component, TimedIdentifiable
from tensortrade.instruments import TradingPair
from tensortrade.data import Module
from tensortrade.data import Forward

from tensortrade.exchanges.exchange import Exchange
import pandas as pd 

class SimulatedExchange(Exchange):
    """An exchange, in which the price history is based off the supplied data frame and
    trade execution is largely decided by the designated slippage model.
    If the `data_frame` parameter is not supplied upon initialization, it must be set before
    the exchange can be used within a trading environment.
    """

    def __init__(self, data_frame: pd.DataFrame = None, **kwargs):
        super().__init__(
            dtype=self.default('dtype', np.float32),
            feature_pipeline=self.default('feature_pipeline', None)
        )

        self._commission_percent = self.default('commission_percent', 0.3, kwargs)
        self._base_precision = self.default('base_precision', 2, kwargs)
        self._instrument_precision = self.default('instrument_precision', 8, kwargs)
        self._min_trade_size = self.default('min_trade_size', 1e-6, kwargs)
        self._max_trade_size = self.default('max_trade_size', 1e6, kwargs)

        self._initial_balance = self.default('initial_balance', 1e4, kwargs)
        self._observation_columns = self.default(
            'observation_columns',
            ['open', 'high', 'low', 'close', 'volume'],
            kwargs
        )
        self._price_column = self.default('price_column', 'close', kwargs)
        self._window_size = self.default('window_size', 1, kwargs)
        self._pretransform = self.default('pretransform', True, kwargs)
        self._price_history = None

        self.data_frame = self.default('data_frame', data_frame)

        model = self.default('slippage_model', 'uniform', kwargs)
        self._slippage_model = slippage.get(model) if isinstance(model, str) else model()
`
You can refer to the documentation here,
https://www.tensortrade.org/en/latest/examples/overview.html

But I am not sure that it will work or not.

I am a newbie in programming, and know python only a little bit, I am just a trader.

**Comment by quantwin** [comment]
from typing import Callable, Union
from decimal import Decimal

from tensortrade.base import Component, TimedIdentifiable
from tensortrade.instruments import TradingPair
from tensortrade.data import Module
from tensortrade.data import Forward

from tensortrade.exchanges.exchange import Exchange
import pandas as pd 

class SimulatedExchange(Exchange):
    """An exchange, in which the price history is based off the supplied data frame and
    trade execution is largely decided by the designated slippage model.
    If the `data_frame` parameter is not supplied upon initialization, it must be set before
    the exchange can be used within a trading environment.
    """

put this at the begin of the py file

**Comment by raznem** [comment]
I have the same issue when trying to run an example from https://towardsdatascience.com/trade-smarter-w-reinforcement-learning-a5e91163f315#a323.
`from tensortrade.exchanges.simulated import FBMExchange` 
returns:
```ModuleNotFoundError: No module named 'tensortrade.exchanges.simulated'```

**Comment by mwbrulhardt** [comment]
This example is deprecated and the structure of TT has changed as a result so this type of exchange is not supported in the current state. This functionality can still be created with the new structure and new tutorials will be coming soon.

**Comment by CodingWookie** [comment]
> This example is deprecated and the structure of TT has changed as a result so this type of exchange is not supported in the current state. This functionality can still be created with the new structure and new tutorials will be coming soon.

Can you point me to the tutorials?

**Comment by ebinxavier** [comment]
> > This example is deprecated and the structure of TT has changed as a result so this type of exchange is not supported in the current state. This functionality can still be created with the new structure and new tutorials will be coming soon.
> 
> Can you point me to the tutorials?

Try this [https://www.tensortrade.org/en/latest/examples/overview.html](url)
