### ISSUE TITLE
ValueError: Invalid format string in examples/train_and_evaluate.ipynb

### ISSUE THREAD

**Issue by quantwin** [tensortrade-org/tensortrade#228]
window 10
python 3.7

the latest tensortrade

When I try to run train_and_evaluate.ipynb in examples, stoped here.

`
from tensortrade.agents import DQNAgent

agent = DQNAgent(env)

agent.train(n_steps=200, save_path="D:\\pythoncode\\examples\\agents")`

`====      AGENT ID: d2ba874a-56a5-41e0-8adc-361606cef808      ====
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-68c13ae32dba> in <module>
      5 # agent.train(n_steps=200, save_path='./examples/agents/')
      6 # agent.train(n_steps=200, save_path="examples/agents/")
----> 7 agent.train(n_steps=200, save_path="D:\\pythoncode\\examples\\agents")

D:\anaconda3\envs\tf2\lib\site-packages\tensortrade\agents\dqn_agent.py in train(self, n_steps, n_episodes, save_every, save_path, callback, **kwargs)
    171 
    172                 if render_interval is not None and steps_done % render_interval == 0:
--> 173                     self.env.render(episode)
    174 
    175                 if steps_done % update_target_every == 0:

D:\anaconda3\envs\tf2\lib\site-packages\tensortrade\environments\trading_environment.py in render(self, episode)
    317                             net_worth=self._portfolio.performance.net_worth,
    318                             performance=self._portfolio.performance.drop(columns=['base_symbol']),
--> 319                             trades=self._broker.trades)
    320 
    321     def save(self):

D:\anaconda3\envs\tf2\lib\site-packages\tensortrade\environments\render\screen_logger.py in render(self, episode, max_episodes, step, max_steps, price_history, net_worth, performance, trades)
     29                performance: pd.DataFrame = None, trades: 'OrderedDict' = None
     30                ):
---> 31         print(self._create_log_entry(episode, max_episodes, step, max_steps, date_format=self._date_format))

D:\anaconda3\envs\tf2\lib\site-packages\tensortrade\environments\render\base_renderer.py in _create_log_entry(self, episode, max_episodes, step, max_steps, date_format)
     29                          step: int = None, max_steps: int = None,
     30                          date_format='%Y-%m-%d %H:%M:%S %p'):
---> 31         log_entry = '[{}]'.format(datetime.now().strftime(date_format))
     32 
     33         if episode is not None:

ValueError: Invalid format string`

**Comment by quantwin** [comment]
I try others,
agent.train(n_steps=200, save_path='./examples/agents/')
or 
agent.train(n_steps=200, save_path="examples/agents/")

All get the same error.

**Comment by Vincces** [comment]
I got the same error. T T

**Comment by yenjanw** [comment]
I got this issue in Windows, but Mac work fine.

**Comment by slachenberg** [comment]
Looks like the default date format used in create_log_entry needs to be updated to something platform agnostic.

You can go ahead and remove strftime(date_format) to get things running in the meantime.

**Comment by t1me0ut** [comment]
Windows uses '\' character to separate folder names un the path while Linux uses '/'. You can do the code multiplatfrom using os package:
agent.train(n_steps=200, save_path=os.path.join(root_path, 'examples', 'agent'))

Where root_path is string with your OS path to tensortrade repo.

**Comment by quantwin** [comment]
> Looks like the default date format used in create_log_entry needs to be updated to something platform agnostic.
> 
> You can go ahead and remove strftime(date_format) to get things running in the meantime.

Thank you, slachenberg. That's really the problem. It works now.

But strangely, I run the following alone, and it works.

>>> date_format = '%Y-%m-%d %H:%M:%S %p'
>>> print(datetime.now().strftime(date_format))
2020-05-16 10:49:15 AM

**Comment by Vincces** [comment]
> > Looks like the default date format used in create_log_entry needs to be updated to something platform agnostic.
> > You can go ahead and remove strftime(date_format) to get things running in the meantime.
> 
> Thank you, slachenberg. That's really the problem. It works now.
> 
> But strangely, I run the following alone, and it works.
> 
> > > > date_format = '%Y-%m-%d %H:%M:%S %p'
> > > > print(datetime.now().strftime(date_format))
> > > > 2020-05-16 10:49:15 AM

Hello,quantwin and slachenberg.I want to know what is the meaning"go ahead and remove strftime(date_format)" ? How to modify the code ? Thank you very much.

**Comment by quantwin** [comment]
def _create_log_entry(self, episode: int = None, max_episodes: int = None,
                         step: int = None, max_steps: int = None,
                         date_format='%Y-%m-%d %H:%M:%S'):
        #log_entry = '[{}]'.format(datetime.now().strftime(date_format))
        log_entry = '[{}]'.format(datetime.now())

        if episode is not None:
