### ISSUE TITLE
About installation and exchanges setting

### ISSUE THREAD

**Issue by quantwin** [tensortrade-org/tensortrade#229]
I have a little problem when install tensortrade.

 I try this at colab.research.google.com,

pip install tensortrade[tf,tensorforce,baselines,ccxt,fbm]

Some packages version are low.

So I try to install it from github directly.
pip install git+https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]

And it can not work too.
Collecting git+https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]
  Cloning https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm] to /tmp/pip-req-build-tarvr9cy
  Running command git clone -q 'https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]' /tmp/pip-req-build-tarvr9cy
  fatal: unable to access 'https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]/': The requested URL returned error: 400
ERROR: Command errored out with exit status 128: git clone -q 'https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]' /tmp/pip-req-build-tarvr9cy Check the logs for full command output.

So I try again on my pc. 

The pip install git+http method seems frozened, so I download it firstly.

D:\Tmp>git clone https://github.com/notadamking/tensortrade.git
D:\Tmp>cd tensortrade
D:\Tmp\tensortrade>pip install -e .
And then I move the tensortrade in the download tensortrade directory to python folder, Lib\site-packages.

At last I also installed other packages,  tf2, tensorforce ,stable_baselines , ccxt , fbm

It seems that tensortrade work now.

But when I tried some examples, I found that there are still many things to do in exchanges.

**Is it necessary to **manually** create those required classes?  Or is there a problem with my installation method, and the correct settings have not been completed**

**Comment by mohammadalimehdizadeh** [comment]
i have the same issue, i want to try github repo examples on Colab but i see many errors?

**Comment by MarkintoshZ** [comment]
This is what works for me
```
!git clone https://github.com/tensortrade-org/tensortrade.git
!cd tensortrade
!python setup.py install
```

**Comment by carlogrisetti** [comment]
@quantwin i know this is obsolete by now, but have you tried with the new repo?

Closing this issue in the meantime, as it is most likely resolved. Add more info \ details with current repo\versions and we'll gladly reopen it.
