### ISSUE TITLE
About ask/bid price, spread and leverage(margin)....

### ISSUE THREAD

**Issue by Ray-0403** [tensortrade-org/tensortrade#230]
It seems that ask/bid price, spread, leverage, margin and tick value of symbol(eg: ES...) are not included in the version now, right? Anyone can help or give some instructions to modify the code?

**Comment by carlogrisetti** [comment]
Almost a year after the fact but... They are indeed not implemented. You can sort of factor in spread by reverse engineering the spread as an exchange commission value, and setting that commission value for that specific exchange. This of course works only in exchanges that apply a fixed spread, and in that case the only downside is that different spreads on different assets would have to be managed with different exchanges alltogether, so it's not at all optimal.

As for the tick value, it's just another field you can have in input. Your choice wheter to rely on technical indicators or on "base value" ticks of the asset, or a mix of those.

Have you got through with modifying\adding such functionalities (maybe in a local fork) ?

Thanks

**Comment by carlogrisetti** [comment]
Closing due to being stale. If there is any progress, just comment here. Thanks!

**Comment by yglpyn8888** [comment]
I also encountered the problem of futures margin, and then search it here. It seems that it has not been implemented yet, which is really sad.
