### ISSUE TITLE
Documentation should be on readthedocs

### ISSUE THREAD

**Issue by chokosabe** [tensortrade-org/tensortrade#235]
The documentation is inaccessible

**Comment by goddy1** [comment]
is she in work?

**Comment by jankrepl** [comment]
Unfortunately I am also unable to open the documentation.

**Comment by dimontalban** [comment]
The documentation is to created with python sphinx. For this, sphinx should be installed. Change in the 'docs/' directory and start Sphinx using 'sphinx-quickstart'. Call up 'make html' to create the documents. I can create this in an issue and check in a pull request. The question is whether it is desired. It is a rudimentary API documentary, that still needs to be done. To improve it, I have to get used to it first.

**Comment by mwbrulhardt** [comment]
The documentation is accessible now. Here is the link: https://www.tensortrade.org/en/latest/.
