### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects  in example/train_and_evaluate.ipynb

### ISSUE THREAD

**Issue by longyue188** [tensortrade-org/tensortrade#236]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensortrader) or on the [TensorTrade Discord](https://discord.gg/ZZ7BGWh) #help-desk channel instead of opening a GitHub issue.</em>

**System information**

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04):
- TensorTrade version:
- TensorFlow version:
- Python version:3.7

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

====      AGENT ID: 6c7e72ef-f098-42df-b71d-ef0322cc9190      ====
{'log_to_stderr': False, 'authkey': b'P.28\x94\xe4\xae\x8e\xb8CIU\xc3dO[\xad\x8b\x13\xcb\xdfPR\xb3\xcct\x84\xc7\x1e\xec\x9a\xd4', 'name': 'ParallelDQNTrainer-1', 'sys_path': ['D:\\python\\tensortrade\\examples', 'D:\\python\\tensortrade', 'd:\\programdata\\anaconda3\\envs\\python37\\python37.zip', 'd:\\programdata\\anaconda3\\envs\\python37\\DLLs', 'd:\\programdata\\anaconda3\\envs\\python37\\lib', 'd:\\programdata\\anaconda3\\envs\\python37', 'D:\\python\\tensortrade\\examples', 'C:\\Users\\tianx\\AppData\\Roaming\\Python\\Python37\\site-packages', 'd:\\programdata\\anaconda3\\envs\\python37\\lib\\site-packages', 'd:\\programdata\\anaconda3\\envs\\python37\\lib\\site-packages\\win32', 'd:\\programdata\\anaconda3\\envs\\python37\\lib\\site-packages\\win32\\lib', 'd:\\programdata\\anaconda3\\envs\\python37\\lib\\site-packages\\Pythonwin', 'd:\\programdata\\anaconda3\\envs\\python37\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\tianx\\.ipython'], 'sys_argv': ['d:\\programdata\\anaconda3\\envs\\python37\\lib\\site-packages\\ipykernel_launcher.py', '-f', 'C:\\Users\\tianx\\AppData\\Roaming\\jupyter\\runtime\\kernel-16e69cd7-4dc5-4c6b-83f6-b434aeaa3d05.json'], 'orig_dir': 'D:\\python\\tensortrade\\examples', 'dir': 'D:\\python\\tensortrade\\examples', 'start_method': 'spawn'}
<ParallelDQNTrainer(ParallelDQNTrainer-1, initial)>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-21717b78d49b> in <module>
     15 agent = ParallelDQNAgent(create_env)
     16 
---> 17 agent.train(n_envs=4, n_steps=200, save_path="agents/")

D:\python\tensortrade\tensortrade\agents\parallel\parallel_dqn_agent.py in train(self, n_steps, n_episodes, save_every, save_path, callback, **kwargs)
    134                                                 eps_end,
    135                                                 eps_decay_steps,
--> 136                                                 update_target_every) for _ in range(n_envs)]
    137 
    138         self._start_optimizer_process(self.model,

D:\python\tensortrade\tensortrade\agents\parallel\parallel_dqn_agent.py in <listcomp>(.0)
    134                                                 eps_end,
    135                                                 eps_decay_steps,
--> 136                                                 update_target_every) for _ in range(n_envs)]
    137 
    138         self._start_optimizer_process(self.model,

D:\python\tensortrade\tensortrade\agents\parallel\parallel_dqn_agent.py in _start_trainer_process(self, create_env, memory_queue, model_update_queue, done_queue, n_steps, n_episodes, eps_start, eps_end, eps_decay_steps, update_target_every)
     73                                              update_target_every)
     74 
---> 75         trainer_process.start()
     76 
     77         return trainer_process

d:\programdata\anaconda3\envs\python37\lib\multiprocessing\process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

d:\programdata\anaconda3\envs\python37\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

d:\programdata\anaconda3\envs\python37\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

d:\programdata\anaconda3\envs\python37\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     87             try:
     88                 reduction.dump(prep_data, to_child)
---> 89                 reduction.dump(process_obj, to_child)
     90             finally:
     91                 set_spawning_popen(None)

d:\programdata\anaconda3\envs\python37\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
     60     print(obj)
---> 61     ForkingPickler(file, protocol).dump(obj)
     62 
     63 #

TypeError: can't pickle _thread.RLock objects

**Comment by zeeshanalipanhwar** [comment]
Did you resolve it, how? Are you `tensortrade` library for env creation?

**Comment by carlogrisetti** [comment]
I had pickle issues in the past while using recent python versions and\or recent modules versions (requirements.txt do not specify an upper bound).

In my environment I froze those packages like these:
```
numpy==1.20.3
plotly==5.3.1
scikit-image==0.18.3
typing-extensions==3.10.0.2
```

Can you try with those versions and let me know?

Also... the suggested way going forward is to abandon the built-in agents and rely to more robust training frameworks such as Ray. Have a look at this example: https://www.tensortrade.org/en/latest/examples/train_and_evaluate_using_ray.html

(closing in the meantime as it's working on old code, please comment again if needed)
