### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by JoseAndresMR** [tensortrade-org/tensortrade#238]
Hi everyone,

I am starting to work with Tensortrade. I am running all not [outdated] examples with master branch. All of them get to an error on a different function each. That makes me think that all of the examples are actually outdated with respect to the current state of the branch.

Would appreciate some guidance on where to begin with the latest changes. Are there any updated examples? Is there something I have missed?

Thanks in advance!

**Comment by alexvaca0** [comment]
There are other examples which are not working: in  setup_environment_tutorial.ipynb, I get an IndexError

**Comment by mwbrulhardt** [comment]
They are currently being worked on. They are functioning on the `enironment-refactor` branch and will be getting merged into `master` soon.

**Comment by JoseAndresMR** [comment]
Great, thank you! In the meanwhile i've been learning with the examples shared in Discord. Highly recommended
