### ISSUE TITLE
Documentation fails

### ISSUE THREAD

**Issue by alexvaca0** [tensortrade-org/tensortrade#247]
The documentation is not built when calling make. 

<pre>Makefile:19: recipe for target &apos;html&apos; failed
make[1]: *** [html] Error 2
make[1]: Leaving directory &apos;/docs&apos;
Makefile:17: recipe for target &apos;docs-build&apos; failed
make: *** [docs-build] Error 2
Makefile:44: recipe for target &apos;run-docs&apos; failed
make: *** [run-docs] Error 2
</pre>

This is the output of the console.

**Comment by mwbrulhardt** [comment]
The documentation is available [here](https://www.tensortrade.org/en/latest/). But if you definitely want to build it then I believe you need to install TT with the docs requirements as well.

**Comment by notadamking** [comment]
> The documentation is available [here](https://www.tensortrade.org/en/latest/). But if you definitely want to build it then I believe you need to install TT with the docs requirements as well.

One way to do this is go to the `/docs` directory and run `pip3 install -r ./requirements.txt`.
