### ISSUE TITLE
Agent train function only completes one episode

### ISSUE THREAD

**Issue by papapumpnz** [tensortrade-org/tensortrade#248]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensortrader) or on the [TensorTrade Discord](https://discord.gg/ZZ7BGWh) #help-desk channel instead of opening a GitHub issue.</em>

**System information**

- Have I written custom code (as opposed to using example directory): No. Default code
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04): Red Hat Enterprise Linux Server release 7.8 (Maipo)
- TensorTrade version: master branch Git
- TensorFlow version: tensorflow==2.3.0
- Python version: 3.8

**Describe the current behavior**
When I run tensortrade.agents.A2CAgent.train function the default behavior is to stop training after 1 episode when all steps have been completed in that episode. Passing variables n_steps=100 and episodes=4. After 100 steps, the training stops only doing 1 episode.

**Describe the expected behavior**
Passing variables n_steps=100 and episodes=4 should run 100 steps of 4 episdoes.

**Code to reproduce the issue**  
In class tensortrade.agents.A2CAgent, function train() the following code block seems to be incorrect.

              if n_steps and steps_done >= n_steps:
                    done = True
                    stop_training = True

Setting stop_training = True does not seem correct here. This should only be set once all episodes have completed, not all steps.

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by TheSnowGuru** [comment]
Better idea to skip episode/ and even steps when acc net_worth dd is bigger than (3%) . This way agent might learn to avoid it.

Maybe Need to add a var:
Skip_episode_dd_thold 


But your suggestion is on the spot and it might be a bug....

Thanks

⁣

**Comment by carlogrisetti** [comment]
@papapumpnz There have been many modifications in the last months. Can you verify the issue is still present?

@TheSnowGuru Also, stopping the training on dropdown would mean that if the agent is able to get a profit, let's say +5% and then would drop down 10%, the "real" result would be that it goes down to -5% net (it's not that, I know, but let's say math works different for simplicity's sake). When the training stops due to the rule you proposed, it would show that the agent has a +2% net margin... and it's not true... it's only true to that specific point.

**Comment by carlogrisetti** [comment]
Closing due to being stale. If there is any progress, just comment here. Thanks!
