### ISSUE TITLE
Changed stochastic package structure 

### ISSUE THREAD

**Issue by smartin-pck** [tensortrade-org/tensortrade#260]
**System information**

- Have I written custom code (as opposed to using example directory): No
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04): Windows 10 - 2004 Subsystem ubuntu 20.04 (WSL 2)
- TensorTrade version: 1.0.0b0
- TensorFlow version: 2.3.1
- Python version: 3.6.9

**Describe the current behavior**
I create a new docker container with makefile and when i want to use an example code i get "from stochastic.noise import GaussianNoise ModuleNotFoundError: No module named 'stochastic.noise' "

The reason of this issue that the stochastic deployed new version and all component has been moved into the stochastic.processes folder and now the GaussianNoise is available from stochastic.processes.noise

**Code to reproduce the issue**  
Create new docker with makefile and run train_and_evaluate.ipynb

**Solution**
Replace the import line int the all python script where it's needed or use older version from stochastic package.

**Comment by rhamnett** [comment]
This appears to have been fixed as per the mention, please re-open if you have further issues.
