### ISSUE TITLE
Import Error: couldn't import GaussianNoise from stochastic.noise

### ISSUE THREAD

**Issue by 51bitquant** [tensortrade-org/tensortrade#261]
Bugs: import Error:
couldn't import GaussianNoise from stochastic.noise

stochastic has change its package structures, for the new version, we need to import like this:

```
from stochastic.processes.noise import GaussianNoise
from stochastic.processes.continuous import FractionalBrownianMotion

```

**Comment by TekpreXyz** [comment]
i think that can close this
