### ISSUE TITLE
Sortino ratio calculation is not correct

### ISSUE THREAD

**Issue by ctstanleylee** [tensortrade-org/tensortrade#267]
For the Sortino ratio calculation, it seems still taking into account the upside_returns?
should add downside_returns[returns >= self._target_returns] = 0 after downside_returns = returns.copy()

Current Sortino ratio calculation:
  downside_returns = returns.copy()
  downside_returns[returns < self._target_returns] = returns ** 2

  expected_return = np.mean(returns)
  downside_std = np.sqrt(np.std(downside_returns))

  return (expected_return - self._risk_free_rate + 1e-9) / (downside_std + 1e-9)

**Comment by carlogrisetti** [comment]
@mwbrulhardt can you check this?

**Comment by mwbrulhardt** [comment]
Shouldn't this computation involve numerical integration of some sort. I've read that the discrete calculations used are actually not correct.  Check the Wikipedia [page](https://en.wikipedia.org/wiki/Sortino_ratio#:~:text=The%20Sortino%20ratio%20measures%20the,upside%20and%20downside%20volatility%20equally.).

**Comment by mwbrulhardt** [comment]
I believe this is what it should look like. I chose the LaPlace distribution for representing the return. That distribution can be replaced with whatever someone believes fits the data the best. Here's what the code would look like.

```python
import numpy as np
import pandas as pd


def laplace(x, loc, scale):
    return (1 / (2*scale))*np.exp(-abs(x - loc) / scale)


def integrand(x, loc, scale, target):
    return (target - x)**2 * laplace(x, loc, scale)


def sortino(returns: pd.Series, target: float = 0) -> float:
    r = returns.values

    loc = np.median(r)
    scale = np.abs(r - loc).mean()

    dv = quad(integrand, -np.inf, target, args=(loc, scale, target))[0]
    dr = np.sqrt(dv)

    return (r.mean() - target) / dr

```

**Comment by carlogrisetti** [comment]
@ctstanleylee does that look good to you?

**Comment by carlogrisetti** [comment]
Stale, closed
