### ISSUE TITLE
HTTP Error 404 @fetch

### ISSUE THREAD

**Issue by frederikvanduuren** [tensortrade-org/tensortrade#269]
hi

trying to run the examples in colab: train_and_evaluate.ipynd

but this fetch:
data = cdd.fetch("Coinbase", "USD", "BTC", "1h")
produces:
HTTPError: HTTP Error 404: Not Found

am i missing something? extra login?install needed?

thanx
fred

**Comment by yoavnativ** [comment]
I have the same issue. Looks like it works with Bitstamp but not with Coinbase

**Comment by frederikvanduuren** [comment]
this does not work either :(
data = cdd.fetch("BitStamp", "USD", "BTC", "1h")

**Comment by yoavnativ** [comment]
I think you have a typo: "Bitstamp" not "BitStamp"
data = cdd.fetch("Bitstamp", "USD", "BTC", "1h")

**Comment by frederikvanduuren** [comment]
YES! thanx
this code is badly updated :(

fred

**Comment by santivill** [comment]
Does it work with binance?. I got the same problem as with Coinbase

**Comment by santivill** [comment]
May I have your help pls?
Thanks
Santi

**Comment by frederikvanduuren** [comment]
only Bitstamp works...
data = cdd.fetch("Bitstamp", "USD", "BTC", "1h")

**Comment by santivill** [comment]
Thanks Fred. 
When is expected will work with binance?
Thanks
Santi

**Comment by rhamnett** [comment]
Please see #283
