### ISSUE TITLE
http://localhost:8892/notebooks/renderers_and_plotly_chart.ipynb

### ISSUE THREAD

**Issue by TekpreXyz** [tensortrade-org/tensortrade#271]
**System information**

- Have I written custom code (as opposed to using example directory):
 Windows 10, 
- TensorTrade version:"1.0.1-beta"
- TensorFlow version: 2.4
- Python version: 3.8

http://localhost:8892/notebooks/renderers_and_plotly_chart.ipynb

![image](https://user-images.githubusercontent.com/73416709/103217221-68217d00-4918-11eb-86b5-c4a8b538ebbb.png)

`c:\users\kit\pycharmprojects\tensortrade\venv\lib\site-packages\ta\trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
c:\users\kit\pycharmprojects\tensortrade\venv\lib\site-packages\ta\trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])

**Comment by carlogrisetti** [comment]
Check your data, you have negative volumes and that doesn't seem right.
TA is a third party library and that is giving you the error.

Might be that you are running some sort of normalization (min-max?) before using TA ?
TA needs raw, non normalized, data to be able to add features

You should also share all the code. If you share a "localhost" link, only you will be able to see it

**Comment by TekpreXyz** [comment]
Grazie
