### ISSUE TITLE
renderers_and_plotly_chart - Direct Performance and Net Worth Plotting - AttributeError: 'collections.OrderedDict' object has no attribute 'plot

### ISSUE THREAD

**Issue by TekpreXyz** [tensortrade-org/tensortrade#273]
![image](https://user-images.githubusercontent.com/73416709/103218064-57720680-491a-11eb-990b-a81aa52e2d82.png)

**Comment by Alsac** [comment]
I run with same error, cannot plot any picture.

**Comment by shuanat** [comment]
Try this one:
`performance = pd.DataFrame.from_dict(env.action_scheme.portfolio.performance, orient='index')
performance.plot()`

**Comment by super999** [comment]
thank u. :)

**Comment by carlogrisetti** [comment]
Fixed in https://github.com/tensortrade-org/tensortrade/commit/2c5cb65b022351fefcc5b3a6f9e88a837d2edec4
sorry for the delay :)
