### ISSUE TITLE
 Render via Ray dashboard don't work on Windows 10 

### ISSUE THREAD

**Issue by TekpreXyz** [tensortrade-org/tensortrade#281]
Render via Ray dashboard seems don't work on Windows 10, there are any other way to see the process working?

**Comment by carlogrisetti** [comment]
Ray dashboard on windows is broken. It's not tensortrade's fault, nor Ray, but something related to Node support on Windows.

You can see the progress at the console output of the main worker, or by using Tensorboard and pointing to the output model folder (even if backend is torch)

**Comment by TekpreXyz** [comment]
Thank!
Grazie Carlo ho risolto!
