### ISSUE TITLE
Unable to fetch data using Cryptodatadownload

### ISSUE THREAD

**Issue by kunwar-vikrant** [tensortrade-org/tensortrade#283]
```
bitstamp = Exchange("bitstamp", service=execute_order)(
    Stream.source(list(bitstamp_btc['close'][-100:]), dtype="float").rename("USD-BTC"),
    Stream.source(list(bitstamp_eth['close'][-100:]), dtype="float").rename("USD-ETH"),
    Stream.source(list(bitstamp_ltc['close'][-100:]), dtype="float").rename("USD-LTC")
)

```

While fetching data there is always an error that:

> NameError: name 'bitstamp_btc' is not defined

**Comment by TekpreXyz** [comment]
bitstamp is oblsolete

**Comment by houmanb** [comment]
I can't even run the "Setup Environment" example from the docs.
I think these errors could be related:

```
cdd.fetch("Coinbase", "USD", "BTC", "1h").add_prefix("BTC:")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/tensortrade/tensortrade/data/cdd.py", line 147, in fetch
...
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

while switching from *Coinbase* to *Bitstamp* seems to works.

```
cdd.fetch("Bitstamp", "USD", "BTC", "1h").add_prefix("BTC:")
```

I thinks, it's not the author's fault rather than *Coinbase* braking/changing their own API.
So it seems that *Coinbase* has [re]moved expected API url.

**Comment by TekpreXyz** [comment]
yes coinbase in not more available, and example and documentation here is not updated

**Comment by kunwar-vikrant** [comment]
Yeah Coinbase is not available but even if you run the cells with only bitstamp , it still throws an error!

**Comment by Cattpot** [comment]
> ```
> bitstamp = Exchange("bitstamp", service=execute_order)(
>     Stream.source(list(bitstamp_btc['close'][-100:]), dtype="float").rename("USD-BTC"),
>     Stream.source(list(bitstamp_eth['close'][-100:]), dtype="float").rename("USD-ETH"),
>     Stream.source(list(bitstamp_ltc['close'][-100:]), dtype="float").rename("USD-LTC")
> )
> ```
> 
> While fetching data there is always an error that:
> 
> > NameError: name 'bitstamp_btc' is not defined

there is no variable called 'bitstamp_btc'
We need more code from you to help you here..

**Comment by kunwar-vikrant** [comment]
[https://github.com/tensortrade-org/tensortrade/blob/master/examples/ledger_example.ipynb](url) It is the ledger_Example code from the tensortrade repo....
this is how it was defined:
`cdd = CryptoDataDownload()
coinbase_btc = cdd.fetch("Coinbase", "USD", "BTC", "1h")
coinbase_eth = cdd.fetch("Coinbase", "USD", "ETH", "1h")

bitstamp_btc = cdd.fetch("Bitstamp", "USD", "BTC", "1h")
bitstamp_eth = cdd.fetch("Bitstamp", "USD", "ETH", "1h")
bitstamp_ltc = cdd.fetch("Bitstamp", "USD", "LTC", "1h")`

**Comment by crushingCodes** [comment]
> Yeah Coinbase is not available but even if you run the cells with only bitstamp , it still throws an error!

I think the problem you are having is you are leaving the references to coinbase, as coinbase and bitstamp are mixed in the same cells, as a quick fix if you comment out the lines with coinbase it will run, just tested it and seems to work.

**Comment by rhamnett** [comment]
Hi, Coinbase is no longer accessible. You can see a list of supported exchanges here http://www.cryptodatadownload.com/data/northamerican/ (View the download links to get the correct exchange name to enter into the fetch method).

If you wish to use an exchange not listed on CryptoDataDownload then you will need to implement it yourself.
