### ISSUE TITLE
Create example for use in a live trading scenario

### ISSUE THREAD

**Issue by rhamnett** [tensortrade-org/tensortrade#299]
Produce documentation and code example for getting agent actions in a way which produces the ability to live trade (doesn't need to implement trading on a specific exchange)

**Comment by sdfsdsdsd** [comment]
@rhamnett i came across this ticket while trying to understand if tensortrade can actually trade live or just help training models.
I am still not sure, but if you can help me to figure out I am happy to write a documentation about it :)

**Comment by t3ch9** [comment]
> 
> 
> @rhamnett i came across this ticket while trying to understand if tensortrade can actually trade live or just help training models.
> I am still not sure, but if you can help me to figure out I am happy to write a documentation about it :)

Did you find out if tensortrade can be used for live trading?

**Comment by eicnix** [comment]
@rhamnett I would like to take on this ticket to produce an example on how to use TensorTrade with ccxt. 

My approach for this would be:
* Implement the ccxt service
* Implement a push feed to first download `n` historical bars and then switch into live mode
* Configure an exchange object to use the new service and push feed
* Prepare a notebook to first train a simple agent and then use it on live trading (in testnet environment)

**Comment by abstractguy** [comment]
This would be where the validation dataset would be used, but not during the earlier trainings. All notebooks will need to be rewritten to handle it.
