### ISSUE TITLE
PlotlyTradingChart Always Showing

### ISSUE THREAD

**Issue by tidues** [tensortrade-org/tensortrade#309]
When calling env.render(), PlotlyTradingChart always showing even when setting the input parameter "display" as False. 

The package I installed is using pip install tensortrade, and the version installed by this is 1.0.1b0.

I checked the source code installed on my local machine and the code in this repository, found some discrepancies:

1. in class PlotlyTradingChart.__init__, the input "display" is never used, and self._show_chart is set to True.
2. in class PlotlyTradingChart.render_env, after "display(self.fig)" there is one line that set self._show_chart = False, which is not in the source code in this repository.
3. in class PlotlyTradingChar.render_env, the last line "self.fig.show()" will show the figure regardless the value of self._show_chart, which is different from the code here.

**Comment by carlogrisetti** [comment]
Hello,
please install using `pip install git+https://github.com/tensortrade-org/tensortrade.git`

It has already been fixed and will be in the next release

**Comment by tidues** [comment]
That works. Thank you!
