### ISSUE TITLE
SimpleOrders action scheme on the Github version works unexpected

### ISSUE THREAD

**Issue by tidues** [tensortrade-org/tensortrade#310]
I am using the github version: `pip install git+https://github.com/tensortrade-org/tensortrade.git`. This addresses the plotly keep showing problem. But, a new problem emerges as the new training results are vastly different from previous well-trained results (old results are using the package from `pip install tensortrade`). It seems that the reason is the action scheme doesn't use any sell actions in training. The following two screenshots are training results of the exact same code with the same parameters. The first is the new training result, the second is the old training result. The action scheme I used is `action =SimpleOrders(trade_sizes=10)`

New result (unexpected): https://flic.kr/p/2kHaYY2
Old result (expected): https://flic.kr/p/2kHeABo

**Comment by fodrh1201** [comment]
I think that the problem exists in get_orders function.
The size of quote should be changed to the base standard.

**Comment by tidues** [comment]
Thanks. Has this been fixed?

**Comment by fodrh1201** [comment]
Yes. agent can use sell action.

**Comment by tidues** [comment]
That's great. Thanks!
