### ISSUE TITLE
Tensorflow version 2

### ISSUE THREAD

**Issue by lefig** [tensortrade-org/tensortrade#318]
Hi,

Firstly, thank you for a great project and several years of hard work behind it.

I recently came across the project and would appreciate asking a question.

What is the current status of Tensorflow 2 support.

Has this been implemented now?

Many thanks

Fig

**Comment by carlogrisetti** [comment]
framework support is mainly dependent on your training framework of choice. We encourage using Ray as it seems to be the most powerful and we're using that to test it too.
I believe it has support for TF, although I've always seen it used with torch.

Can you elaborate on that? :)

**Comment by carlogrisetti** [comment]
Closing due to no response
