### ISSUE TITLE
The sell Oder here is only a way to close buy order?

### ISSUE THREAD

**Issue by Ray-0403** [tensortrade-org/tensortrade#324]
If it is, any advice on how to modify action scheme and oms system to support real sell order? How to make it can only hold or not hold one order one time and just close the whole order when it want rather than send another sell order with different size to partially close the buy order?

**Comment by carlogrisetti** [comment]
It is currently implemented only with long positions, so buy and sell are the opening and closing of a long position. I can't tell you how to proceed but I don't remember who in the past said that it would need extensive modification to the OMS and all related code that deals with the portfolio

As per the current implementation, you can make it buy and sell partial quantities by not using the BSH action scheme. Have a look at simpleorders for example.
