### ISSUE TITLE
Missing "ipywidgets>=7.0.0" on the examples' requirements

### ISSUE THREAD

**Issue by munirjojoverge** [tensortrade-org/tensortrade#328]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensortrader) or on the [TensorTrade Discord](https://discord.gg/ZZ7BGWh) #help-desk channel instead of opening a GitHub issue.</em>

**System information**

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04): Ubuntu 20.04
- TensorTrade version: v1.0.3
- TensorFlow version: 2.5.0 
- Python version: 3.6 inside docker (3.7 on machine)

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.__version__)"

**Describe the current behavior**
Fails to run last cell on train_and_evaluate.ipynb

**Describe the expected behavior**
It should train without failing 

**Code to reproduce the issue**  
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
train_and_evaluate.ipynb

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by carlogrisetti** [comment]
Thanks for the tip!
