### ISSUE TITLE
timed criteria possible error

### ISSUE THREAD

**Issue by ava6969** [tensortrade-org/tensortrade#331]
def check(self, order: 'Order', exchange: 'Exchange'):
        return (order.clock.step - order.created_at) <= self.duration 

// this looks  like it should be this
 def check(self, order: 'Order', exchange: 'Exchange'):
        return (order.clock.now() - order.created_at) <= self.duration

**Comment by carlogrisetti** [comment]
@rhamnett did you manage to look into that or did it pass under the radar? :)

Thanks

**Comment by abstractguy** [comment]
A lot of tests are using past data, so I wouldn't do that. Please close the issue.

**Comment by rhamnett** [comment]
Don't believe this to be a current issue, Please re-open if you disagree.
