### ISSUE TITLE
Test Unseen data

### ISSUE THREAD

**Issue by yosoul93** [tensortrade-org/tensortrade#333]
There is no example on how to test an unseen data

**Comment by carlogrisetti** [comment]
If using Ray (which is the suggested framework to choose), you can specify an `evaluation_config` parameter, in which you can specify a different value for a configuration variable, that is set only during evaluation.
Having a "is_evaluation" set to False in the normal training configuration, and set to True in the evaluation configuration, allows you to pilot data retrieval in the environment build function.

Based on that variable you could load training data during training and load evaluation (unseen) data during evaluation.
This also has the plus of having the evaluation statistics reported within Tensorboard by Ray.
Remember also to set `evaluation_interval `to the number of iterations that has to pass to perform an evaluation.

**Comment by rhamnett** [comment]
@carlogrisetti can we get a simple example for this in the repo?

**Comment by carlogrisetti** [comment]
I am working on one... As soon as it's ironed out I can commit something rough, but usable.

We definitely need to deprecate the built-in agents thou, they create too much dispersion (see PRs), in favor of supporting Ray. I am currently using the latest builds and they seem to be working good, even with this evaluation thing (they weren't before).

**Comment by rhamnett** [comment]
I agree, I can spend some time removing them soon

**Comment by carlogrisetti** [comment]
@yosoul93 can you have a look at [THIS](https://github.com/tensortrade-org/tensortrade/blob/docs-ray-training-example/docs/source/examples/train_and_evaluate_using_ray.md) updated doc and let me know if it's easy enough to be published as-is?
It is the result of a lot of copypasta from some of the code I am working on, removing some private info. I haven't had time to test it yet in its entirety.

**Comment by wnz99** [comment]
Hi,
I've noticed you mentioned deprecating the built-in agents, but would it be possible to expand this tutorial to include processing of test data?

For example I tried something like the following:

```python
episode_reward = 0
done = False
obs = env.reset()

env_eval = default.create(
    portfolio=portfolio,
    action_scheme="managed-risk",
    reward_scheme="risk-adjusted",
    feed=feed,
    window_size=20,
    renderer_feed=renderer_feed,
    renderer=[
        chart_renderer,
    ]
)

obs = env_eval.reset()

while not done:
    action = agent.get_action(obs)
    obs, reward, done, info = env_eval.step(action)
    episode_reward += reward
    env_eval.render()


env_eval.save()
```

However the chart does not show trading actions and also I'm not sure how to get them at all. It would be great to have an example showing how to feed live data to an agent (as setup in that page) in order to make do some real trading. Something simple.

**Comment by carlogrisetti** [comment]
In the meantime, the documentation was built and the same tutorial\example is available here: https://www.tensortrade.org/en/latest/examples/train_and_evaluate_using_ray.html

You get the action by picking the next "action" from the while loop you wrote, assuming that env_eval is containing the latest data available. Its format will depend on the action space you have available (ie: in a BSH action scheme you will have a binary buy\sell signal as output)

**Comment by carlogrisetti** [comment]
@wnz99 have you been able to test the example doc?

**Comment by abstractguy** [comment]
> I am working on one... As soon as it's ironed out I can commit something rough, but usable.
> 
> We definitely need to deprecate the built-in agents thou, they create too much dispersion (see PRs), in favor of supporting Ray. I am currently using the latest builds and they seem to be working good, even with this evaluation thing (they weren't before).

I wouldn't deprecate agents yet. I've been working on a replacement but wouldn't deprecate without a replacement. It does show how to reuse the library on other reinforcement learning frameworks from the ground up. It's valuable examples that just need replacements

**Comment by abstractguy** [comment]
Done. See examples/use_attentionnet_rllib.ipynb
It should be copied to the other example notebooks though. Anyone could do it

**Comment by carlogrisetti** [comment]
Closing as obsolete. Please reopen this issue if there is any further development do discuss regarding evaluation
