### ISSUE TITLE
Update in documentation of SimpleProfit reward scheme

### ISSUE THREAD

**Issue by Zymoo** [tensortrade-org/tensortrade#337]
Hello,
It seems that in the documentation [here](https://www.tensortrade.org/en/latest/components/reward_scheme.html), there is this information: "The simple profit scheme returns a reward of -1 for not holding a trade, 1 for holding a trade, 2 for purchasing an instrument, and a value corresponding to the (positive/negative) profit earned by a trade if an instrument was sold.". 

However looking the SimpleProfit class it just seems to be the increase in the portfolio value, without adding or substracting points for holding trade.

If I somehow overlooked something please leave a comment.
Thanks!

**Comment by carlogrisetti** [comment]
@Zymoo seems to me you are perfectly right. There is nothing more on the reward calculation than the actual profit. That most probably is an old comment to one of the first implementations of the SimpleReward.
More sophisticated implementations have been done in the `Risk Adjusted Returns` and `Position-based Returns` reward schemes.

#354 fixes the documentation regarding this. It will be correct as soon as it will be merged.
