### ISSUE TITLE
BUG: wrong cumulative rewards calculation in rewards.SimpleProfit

### ISSUE THREAD

**Issue by sadimoodi** [tensortrade-org/tensortrade#350]
Hello,

Looking at classtensortrade.env.default.rewards.SimpleProfit the author claims that **get_reward method Returns:    float – The cumulative percentage change in net worth over the previous window_size time steps.**, code:
        net_worths = [nw['net_worth'] for nw in portfolio.performance.values()]
        returns = [(b - a) / a for a, b in zip(net_worths[::1], net_worths[1::1])]
        returns = np.array([x + 1 for x in returns[-self._window_size:]]).cumprod() -1

seems to me an incorrect way of calculating what he claims to be "cumulative percentage change in net worth"? 
I have changed the code to:
net_worths = [nw['net_worth'] for nw in portfolio.performance.values()]
        returns = [(b - a) / a for a, b in zip(net_worths[::1], net_worths[1::1])]
        returns =np.array(returns)[-self._window_size:].sum()
        return returns

Does that make sense to anyone?

**Comment by carlogrisetti** [comment]
Could you submit a PR with that same code so that we can discuss inline?
Seems to me there is some misinterpretation on the cumulative percentage change (vs. absolute value change)

If today you do +100% and tomorrow you do -50% you're back to the starting point, with a net gain of 0%. With your calculation it seems to me that you would end up reporting +50% (+100-50)

Am I missing something?

**Comment by sadimoodi** [comment]
@carlogrisetti I have created a new PR [here ](https://github.com/tensortrade-org/tensortrade/pull/352)

**Comment by carlogrisetti** [comment]
@rhamnett are you sure that the calculation is correct? Take a look at my previous comment. I would love a "positive" feedback on top of the PR

**Comment by rhamnett** [comment]
@carlogrisetti sorry perhaps I misunderstood the conversation with @mwbrulhardt  in discord?

**Comment by carlogrisetti** [comment]
Oh, haven't seen discord :)

**Comment by carlogrisetti** [comment]
Closed as misinterpretation. Overall percentage change is not simply a sum of the various percentage changes that occured.
