### ISSUE TITLE
Hello, I would like to ask if the RL algorithm written in pytorch can train the environment generated by tensortrade?

### ISSUE THREAD

**Issue by yglpyn8888** [tensortrade-org/tensortrade#355]
**System information**
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04):  WIN10
- TensorTrade version: latest
- Python version: 3.7

**Comment by rhamnett** [comment]
Sorry can you please explain in more detail what you are looking for ?

**Comment by yglpyn8888** [comment]
Hi, i thought my question was quite clear.. 
Can the RL agent implemented by pytorch train tensortrade environment?

**Comment by rhamnett** [comment]
You don't seem to have reformulated the question in any more detail. Please do so and then re-open the issue.

**Comment by rhamnett** [comment]
We are using RLLIb which has a pytorch implementation that can be used to train TT environment if that is what you mean

**Comment by yglpyn8888** [comment]
> We are using RLLIb which has a pytorch implementation that can be used to train TT environment if that is what you mean

yes that's what i mean!

**Comment by rhamnett** [comment]
just configure "framework" : "torch" (see ray example)

**Comment by yglpyn8888** [comment]
> just configure "framework" : "torch" (see ray example)

ok,  thanks!
