### ISSUE TITLE
Ray trading example.

### ISSUE THREAD

**Issue by wnz99** [tensortrade-org/tensortrade#356]
Hi,

I think there might be an issue in the new Ray example:

This parameter is not used in the `create_env` function:

https://github.com/tensortrade-org/tensortrade/blob/30868039ad35a1894fb78198a9859f0b81485f57/docs/source/examples/train_and_evaluate_using_ray.md?plain=1#L169

And this also seems not used anywhere: 

https://github.com/tensortrade-org/tensortrade/blob/30868039ad35a1894fb78198a9859f0b81485f57/docs/source/examples/train_and_evaluate_using_ray.md?plain=1#L168

**Comment by rhamnett** [comment]
@carlogrisetti  I think we should have this:

```
    reward_scheme = default.rewards.SimpleProfit(window_size=config["reward_window_size"])  # Arbitrarily set as 7
    action_scheme = default.actions.BSH(cash=cash, asset=asset)
    
    env = default.create(
            feed=feed,
            portfolio=portfolio,
            action_scheme=action_scheme,
            reward_scheme=reward_scheme,
            renderer_feed=renderer_feed,
            renderer=[],
            window_size=config["window_size"],
            max_allowed_loss=config["max_allowed_loss"] 
        )
```

**Comment by carlogrisetti** [comment]
Nice catch!
