### ISSUE TITLE
SimpleProfit type 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by wnz99** [tensortrade-org/tensortrade#357]
This change will now lead to the following error:

https://github.com/tensortrade-org/tensortrade/commit/4e12082ee49df5182ec54e9badd6abea14c6cfa0?diff=split

```
(pid=2940865)   File "/home/whitenoise/anaconda3/envs/stock-trading/lib/python3.9/site-packages/tensortrade/env/default/rewards.py", line 78, in get_reward
(pid=2940865)     return 0 if len(returns) < 1 else returns[-1]
(pid=2940865) TypeError: object of type 'numpy.float64' has no len()
```

I tried to revert the change and the issue is solved.

It looks to me that `returns` is no longer expected to be an array and should just be returned by the function.

**Comment by rhamnett** [comment]
Thanks, this was reverted afterwards https://github.com/tensortrade-org/tensortrade/commit/18848be19b698f291513d54cc6b7e0bf01c249dd please git pull 👍🏼
