### ISSUE TITLE
does TensorTrade framework compatibled with pytorch agents?

### ISSUE THREAD

**Issue by yglpyn8888** [tensortrade-org/tensortrade#358]
I found that I seemed to have misunderstood the meaning in issue #355, 
because when I read the document, I found this sentence: "however, the TensorTrade framework is compatible with many reinforcement learning libraries such as Tensorforce, Ray’s RLLib, OpenAI’s Baselines, Intel’s Coach, **or anything from the TensorFlow line such as TF Agents**" 
So algorithms implemented by PYTORCH such as stable baselines3 can train TensorTrade environment? thx!

**Comment by adiyaDalat** [comment]
Also have same question. Does it compatible with stable baselines3?

thanks!
