### ISSUE TITLE
renderers and plotly chart ipnyb net worth plot

### ISSUE THREAD

**Issue by AndyVall** [tensortrade-org/tensortrade#364]
I had to change "#portfolio.performance.net_worth.plot()" to "performance.net_worth.plot()" in  tensortrade/examples/renderers_and_plotly_chart.ipynb input 15. As is, there was no plot available, and playing around with it, it was just the last net worth value. By changing it to performance.net_worth, I got a series of data, like what you had in the example. I am not sure what changed in the library to make this an issue, I believe I am using the latest version in nearly everything.

**Comment by HadiSDev** [comment]
@AndyVall  I just tried with matplotlib and the plotly renderer. I can confirm it is not working

**Comment by AndyVall** [comment]
Try it with my change

**Comment by carlogrisetti** [comment]
Thanks for the tip :)
