### ISSUE TITLE
Using Ray with TensorTrade example isn't working

### ISSUE THREAD

**Issue by SergeySypalo** [tensortrade-org/tensortrade#366]
Hi team,

I'm trying to follow Using Ray with TensorTrade example code, running section by section, but stuck at the
analysis = tune.run(
....
)
section
All code has been copied as-is from the official guide
I have GeForce 1080 in my system
I'm using Python 3.9
Tensorflow version 2.7
All dependencies installed via pip
Manually installed CUDA Toolkit 11.5
Manually downloaded and extracted CuDNN
CUDA Toolkit is in env path
Tensorflow sees my video card

But I'm getting this error:
FileNotFoundError

What file it's looking for?
I changed dir to the directory where the code is located before running it.
The full trace below:

`FileNotFoundError                         Traceback (most recent call last)
d:\repos\trading-bot\dev\ttrd\example.py in <module>
    150 
    151 register_env("TradingEnv", create_env)
--> 152 analysis = tune.run(
    153     "PPO",
    154     stop={

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\tune\tune.py in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, loggers, _remote)
    309 
    310     if not trial_executor or isinstance(trial_executor, RayTrialExecutor):
--> 311         _ray_auto_init()
    312 
    313     if _remote:

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\tune\tune.py in _ray_auto_init()
    749                     "For cluster usage or custom Ray initialization, "
    750                     "call `ray.init(...)` before `tune.run`.")
--> 751         ray.init()

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\_private\client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\worker.py in init(address, num_cpus, num_gpus, resources, object_store_memory, local_mode, ignore_reinit_error, include_dashboard, dashboard_host, dashboard_port, job_config, configure_logging, logging_level, logging_format, log_to_driver, namespace, runtime_env, _enable_object_reconstruction, _redis_max_memory, _plasma_directory, _node_ip_address, _driver_object_store_memory, _memory, _redis_password, _temp_dir, _metrics_export_port, _system_config, _tracing_startup_hook, **kwargs)
    886         # handler. We still spawn a reaper process in case the atexit handler
    887         # isn't called.
--> 888         _global_node = ray.node.Node(
    889             head=True,
    890             shutdown_at_exit=False,

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\node.py in __init__(self, ray_params, head, shutdown_at_exit, spawn_reaper, connect_only)
    246         # Start processes.
    247         if head:
--> 248             self.start_head_processes()
    249             redis_client = self.create_redis_client()
    250             redis_client.set("session_name", self.session_name)

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\node.py in start_head_processes(self)
    903         assert self._redis_address is None
    904         # If this is the head node, start the relevant head node processes.
--> 905         self.start_redis()
    906 
    907         self.start_gcs_server()

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\node.py in start_redis(self)
    713              self._node_ip_address,
    714              redis_log_files,
--> 715              self.get_resource_spec(),
    716              port=self._ray_params.redis_port,
    717              redis_shard_ports=self._ray_params.redis_shard_ports,

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\node.py in get_resource_spec(self)
    366             num_cpus, num_gpus, memory, object_store_memory, resources = \
    367                 merge_resources(env_resources, self._ray_params.resources)
--> 368             self._resource_spec = ResourceSpec(
    369                 self._ray_params.num_cpus
    370                 if num_cpus is None else num_cpus, self._ray_params.num_gpus

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\_private\resource_spec.py in resolve(self, is_head, node_ip_address)
    147         if num_gpus is None:
    148             # Try to automatically detect the number of GPUs.
--> 149             num_gpus = _autodetect_num_gpus()
    150             # Don't use more GPUs than allowed by CUDA_VISIBLE_DEVICES.
    151             if gpu_ids is not None:

~\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\_private\resource_spec.py in _autodetect_num_gpus()
    239         props = "AdapterCompatibility"
    240         cmdargs = ["WMIC", "PATH", "Win32_VideoController", "GET", props]
--> 241         lines = subprocess.check_output(cmdargs).splitlines()[1:]
    242         result = len([x.rstrip() for x in lines if x.startswith(b"NVIDIA")])
    243     return result

~\AppData\Local\Programs\Python\Python39\lib\subprocess.py in check_output(timeout, *popenargs, **kwargs)
    422         kwargs['input'] = empty
    423 
--> 424     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    425                **kwargs).stdout
    426 

~\AppData\Local\Programs\Python\Python39\lib\subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    503         kwargs['stderr'] = PIPE
    504 
--> 505     with Popen(*popenargs, **kwargs) as process:
    506         try:
    507             stdout, stderr = process.communicate(input, timeout=timeout)

~\AppData\Local\Programs\Python\Python39\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, user, group, extra_groups, encoding, errors, text, umask)
    949                             encoding=encoding, errors=errors)
    950 
--> 951             self._execute_child(args, executable, preexec_fn, close_fds,
    952                                 pass_fds, cwd, env,
    953                                 startupinfo, creationflags, shell,

~\AppData\Local\Programs\Python\Python39\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session)
   1418             # Start the process
   1419             try:
-> 1420                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1421                                          # no special security
   1422                                          None, None,

FileNotFoundError: [WinError 2] Unable to find requested file`

**Comment by carlogrisetti** [comment]
`All code has been copied as-is from the official guide` lets me think that you might have also copied the part where you load your csvfile as-is (and you might not have it in the same path as I did writing the sample code).
If you run the ray.init part with `local_mode=True` as a parameter, it should spit out something more, since it is not running in a threaded mode. Please note that this is for debugging purposes only, as it defeats what Ray was born for (distributed execution).

Can you check and report back?

**Comment by SergeySypalo** [comment]
Searched the page I was talking about: https://www.tensortrade.org/en/latest/tutorials/ray.html for the keyword **csv** - can't find it.
So I didn't get what do you mean by "copied the part where you load your CSV file as-is",
Also tried to install a lower version of Python, this time 3.8, still no go, same issue

**Comment by carlogrisetti** [comment]
I am sorry, I thought you were referring to the most recent example: https://www.tensortrade.org/en/latest/examples/train_and_evaluate_using_ray.html

That one uses recent components and is up to date.

Documentation needs a huge cleanup :)

**Comment by carlogrisetti** [comment]
Please reopen this issue if you are still unable to run the example
