### ISSUE TITLE
Unable to install additional features

### ISSUE THREAD

**Issue by tshiamotman** [tensortrade-org/tensortrade#377]
Getting error when installing additional features

For "pip install git+https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]" 
I get the error:

"Collecting git+https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]
  Cloning https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm] to /tmp/pip-req-build-yinma2e8
  Running command git clone -q 'https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]' /tmp/pip-req-build-yinma2e8
  fatal: unable to access 'https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]/': The requested URL returned error: 400
ERROR: Command errored out with exit status 128: git clone -q 'https://github.com/notadamking/tensortrade.git[tf,tensorforce,baselines,ccxt,fbm]' /tmp/pip-req-build-yinma2e8 Check the logs for full command output."

And for the command "pip install tensortrade[tf,tensorforce,baselines,ccxt,fbm]"
I get the following

"WARNING: tensortrade 1.0.4.dev0 does not provide the extra 'baselines'
  WARNING: tensortrade 1.0.4.dev0 does not provide the extra 'ccxt'
  WARNING: tensortrade 1.0.4.dev0 does not provide the extra 'fbm'
  WARNING: tensortrade 1.0.4.dev0 does not provide the extra 'tensorforce'
  WARNING: tensortrade 1.0.4.dev0 does not provide the extra 'tf'"

**Comment by carlogrisetti** [comment]
Can you tell me which document are you following? It's most certainly an obsolete one, and would like to mark it as such in some way.

**Comment by tshiamotman** [comment]
https://tensortradex.readthedocs.io/en/latest/overview/getting_started.html#installation

**Comment by carlogrisetti** [comment]
Damn... thanks. Will fix that :)

**Comment by carlogrisetti** [comment]
Please be aware that you are referring to the documentation for a fork of the project, and not the official one (that you can find on tensortrade.org). In any case those were old references to the way TensorTrade package was splitted up in different components.
The "vanilla" pip install now takes care of everything you need.

Closing as fixed
