### ISSUE TITLE
Feature Request: tensortrade should support gymnasium style environments and APIs, rather than old gym environment

### ISSUE THREAD

**Issue by imperator-git** [tensortrade-org/tensortrade#460]
**Request**:
Could the tensortrade team please help to support the new gymnasium environments? 

**Details**:
Tensortrade is leveraging gym environment, but gym project is no longer maintained and got moved to gymnasium in 2021.
Learn more about the most important changes here: https://github.com/openai/gym and here: https://github.com/Farama-Foundation/Gymnasium

**My Motivation**:
Specifically I am having trouble using tensortrade 1.0.3 together with ray 2.3.0 - because from ray 2.3.0 on, RLlib only supports the new  gymnasium style Env APIs, and now ray gives error that gym style environments (which is used inside tensortrade) is no longer supported ("ValueError: Your environment (<TradingEnv instance>) does not abide to the new gymnasium-style API!").

The ray error gives already some hints how to approach such change:

1 Run `pip install gymnasium` on your command line.
2 Change all your import statements in your code from
   `import gym` -> `import gymnasium as gym` OR
   `from gym.space import Discrete` -> `from gymnasium.spaces import Discrete`
For your custom (single agent) gym.Env classes:
3.1 Either wrap your old Env class via the provided `from gymnasium.wrappers import EnvCompatibility` wrapper class.
3.2 Alternatively to 3.1:
 - Change your `reset()` method to have the call signature 'def reset(self, *, seed=None, options=None)'
 - Return an additional info dict (empty dict should be fine) from your `reset()` method.
 - Return an additional `truncated` flag from your `step()` method (between `done` and `info`). This flag should indicate, whether the episode was terminated prematurely  due to some time constraint or other kind of horizon setting

Thanks a lot for your consideration and I highly appreciate your work on this super tensortrade project.

**Comment by grizzlybearg** [comment]
I second..

**Comment by nexsys** [comment]
I am also having lots of difficulties in order to make it working with latest ray version

**Comment by pavelpichrt** [comment]
Please address this ASAP, I had to downgrade to 2.2.x to make Ray work.

**Comment by lyzyn** [comment]
Have you resolved it? My question is exactly the same as yours.

**Comment by lyzyn** [comment]
> 为了使其与最新的射线版本一起工作，我也遇到了很多困难

Have you resolved it? My question is the same as yours. It is also to use the latest version of Ray.

**Comment by imperator-git** [comment]
As workaround I used the fork https://github.com/MaxLoedige/tensortrade which supports gymnasium style environments.

**Comment by carlogrisetti** [comment]
Thanks for the reference to MaxLoedige fork!
