### ISSUE TITLE
Feature Request: Implement ActionStrategy and InstrumentExchange to support Equities markets

### ISSUE THREAD

**Issue by dahifi** [tensortrade-org/tensortrade#52]
I realize that this library is primarily aimed at crypto markets, but I do a lot of equities trading and would like to help contribute. 

I see that Adam has a stub for the IBKR API, but it doesn't look like there's been much action on it. There also doesn't seem to be much in the way of IB-related packages out there. The closest thing I can find is the Bankroll project. https://github.com/bankroll-py/bankroll. Downside to this library is that it appears to be read-only. 

Putting this issue up as a temperature check to see if anyone's aware of any other suitable candidates for integrating into this package, and to gauge interest in incorporating it into this library. 

As an aside, I've been using an Alpha Vantage module to pull equities data into Pandas, so this could serve as another data source that could be integrated.

**Comment by notadamking** [comment]
> I realize that this library is primarily aimed at crypto markets, but I do a lot of equities trading and would like to help contribute.

Quite the contrary, though that was the initial focus, the framework is aimed at all trading markets: equities, forex, crypto, futures, etc. We would love to have more equities components implemented, if you are up to contribute!

**Comment by dahifi** [comment]
Looking at bankroll, it seems to rely on IBKR for realtime data and CSV imports for the other brokerages, none of which are the one that I actively use. 

There's already a module for Alpha Vantage that works to Pandas. I'm see if I can stub it out and start working on that. Having read access through their API will probably be low-hanging fruit.
