### ISSUE TITLE
Tutorial Fail to run 

### ISSUE THREAD

**Issue by Kalelv45** [tensortrade-org/tensortrade#99]
While Running inside Jupyter Notebook 'TensorTrade_Tutorial.ipynb' file, I get this error and can't continue: 

from tensortrade.actions import DiscreteActionStrategy
action_strategy = DiscreteActionStrategy(n_actions=20, instrument_symbol='BTC')

ERROR: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-ea5ba9b1e05e> in <module>
----> 1 from tensortrade.actions import DiscreteActionStrategy
      2 
      3 action_strategy = DiscreteActionStrategy(n_actions=20, instrument_symbol='BTC')

ImportError: cannot import name 'DiscreteActionStrategy' from 'tensortrade.actions' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensortrade/actions/__init__.py)

Does anyone have the same problem?

**Comment by junfang2019** [comment]
For the newest edition, the TensorTrade_Tutorial.ipynb run smoothly. 
Would you please attach your TensorTrade edition?

or you can update yours to the latest edition.

pip3.7 install git+git://github.com/notadamking/tensortrade.git -U

**Comment by Kalelv45** [comment]
Thanks a lot, seems to work just fine now.

**Comment by junfang2019** [comment]
IMHO, this problem is the python environment setup problem. I use in raw python, did not set up this inside docker. Maybe you can try this.

Or you can copy the code outside Jupiter notebook in any IDE, e.g. PyCharm

**Comment by Kalelv45** [comment]
I was able to arrive till this point: 
import pandas as pd
from tensortrade.environments import TradingEnvironment
from tensortrade.exchanges.simulated import SimulatedExchange

df = pd.read_csv('data/Coinbase_BTCUSD_d.csv', skiprows=1)
exchange = SimulatedExchange(data_frame=df,
                             feature_pipeline=feature_pipeline,
                             base_instrument='USD',
                             pretransform=True)

environment = TradingEnvironment(exchange=exchange,
                                 action_scheme=action_scheme,
                                 reward_scheme=reward_scheme)

new_strategy.environment = environment

test_performance = new_strategy.run(steps=2000)


I get this error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-82d282163c12> in <module>
      7                              feature_pipeline=feature_pipeline,
      8                              base_instrument='USD',
----> 9                              pretransform=True)
     10 
     11 environment = TradingEnvironment(exchange=exchange,

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensortrade/base/component.py in __call__(cls, *args, **kwargs)
     18         instance = cls.__new__(cls, *args, **kwargs)
     19         setattr(instance, 'context', Context(**config))
---> 20         instance.__init__(*args, **kwargs)
     21 
     22         return instance

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensortrade/exchanges/simulated/simulated_exchange.py in __init__(self, data_frame, **kwargs)
     37             dtype=self.default('dtype', np.float32),
     38             feature_pipeline=self.default('feature_pipeline', None),
---> 39             **kwargs
     40         )
     41 

TypeError: __init__() got multiple values for keyword argument 'feature_pipeline'

**Comment by ramoslin02** [comment]
the feature_pipeline is not the argument in the initialization method, if you want to assign the feature_pipeline to the exchange, you can do it like this:
-> exchange.feature_pipeline = feature_pipeline

**Comment by RusEu** [comment]
I think the documentation is outdated .. I also get this problems.
Searching in the code.. I see no DiscreteActions class nowhere

**Comment by mwbrulhardt** [comment]
`DiscreteActions` is no longer in the library. Also there are other relevant issues referencing the failing tutorials that are more recent.
